package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * meterLogStruct
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class meterLogStruct extends Entry {

	public HEX meterLogID = 
			new HEX(8);

	public BYTE meterLogType = 
			new BYTE();

	public TIMESTAMP meterLogTime = 
			new TIMESTAMP(7);

	public TIMESTAMP meterLogStartTime = 
			new TIMESTAMP(7);

	public TIMESTAMP meterLogEndTime = 
			new TIMESTAMP(7);

	public BYTE meterLogResult = 
			new BYTE();

	public UINT meterLogElapse = 
			new UINT();

	public BYTE meterLogTryCount = 
			new BYTE();

	@XmlTransient
	public HEX getMeterLogID()
	{
		 return this.meterLogID;
	}

	public void setMeterLogID(HEX meterLogID)
	{
		 this.meterLogID=meterLogID;
	}

	@XmlTransient
	public BYTE getMeterLogType()
	{
		 return this.meterLogType;
	}

	public void setMeterLogType(BYTE meterLogType)
	{
		 this.meterLogType=meterLogType;
	}

	@XmlTransient
	public TIMESTAMP getMeterLogTime()
	{
		 return this.meterLogTime;
	}

	public void setMeterLogTime(TIMESTAMP meterLogTime)
	{
		 this.meterLogTime=meterLogTime;
	}

	@XmlTransient
	public TIMESTAMP getMeterLogStartTime()
	{
		 return this.meterLogStartTime;
	}

	public void setMeterLogStartTime(TIMESTAMP meterLogStartTime)
	{
		 this.meterLogStartTime=meterLogStartTime;
	}

	@XmlTransient
	public TIMESTAMP getMeterLogEndTime()
	{
		 return this.meterLogEndTime;
	}

	public void setMeterLogEndTime(TIMESTAMP meterLogEndTime)
	{
		 this.meterLogEndTime=meterLogEndTime;
	}

	@XmlTransient
	public BYTE getMeterLogResult()
	{
		 return this.meterLogResult;
	}

	public void setMeterLogResult(BYTE meterLogResult)
	{
		 this.meterLogResult=meterLogResult;
	}

	@XmlTransient
	public UINT getMeterLogElapse()
	{
		 return this.meterLogElapse;
	}

	public void setMeterLogElapse(UINT meterLogElapse)
	{
		 this.meterLogElapse=meterLogElapse;
	}

	@XmlTransient
	public BYTE getMeterLogTryCount()
	{
		 return this.meterLogTryCount;
	}

	public void setMeterLogTryCount(BYTE meterLogTryCount)
	{
		 this.meterLogTryCount=meterLogTryCount;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("meterLogID: " + meterLogID + "\n");
		sb.append("meterLogType: " + meterLogType + "\n");
		sb.append("meterLogTime: " + meterLogTime + "\n");
		sb.append("meterLogStartTime: " + meterLogStartTime + "\n");
		sb.append("meterLogEndTime: " + meterLogEndTime + "\n");
		sb.append("meterLogResult: " + meterLogResult + "\n");
		sb.append("meterLogElapse: " + meterLogElapse + "\n");
		sb.append("meterLogTryCount: " + meterLogTryCount + "\n");


        return sb.toString();
    }
}
