
package com.aimir.fep.command.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-01-11T13:33:56.627+09:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "Exception", targetNamespace = "http://server.ws.command.fep.aimir.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.aimir.fep.command.ws.client.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.aimir.fep.command.ws.client.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.aimir.fep.command.ws.client.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.aimir.fep.command.ws.client.Exception getFaultInfo() {
        return this.exception;
    }
}
