package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * timeEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 * <pre>
 * &lt;complexType name="timeEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{http://server.ws.command.fep.aimir.com/}entry">
 *       &lt;sequence>
 *         &lt;element name="timeYear" type="{http://server.ws.command.fep.aimir.com/}word" minOccurs="0"/>
 *         &lt;element name="timeMon" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="timeDay" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="timeHour" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="timeMin" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="timeSec" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "timeEntry", propOrder = {
    "timeYear",
    "timeMon",
    "timeDay",
    "timeHour",
    "timeMin",
    "timeSec"
})
public class timeEntry extends Entry {

	public WORD timeYear = 
			new WORD();

	public BYTE timeMon = 
			new BYTE();

	public BYTE timeDay = 
			new BYTE();

	public BYTE timeHour = 
			new BYTE();

	public BYTE timeMin = 
			new BYTE();

	public BYTE timeSec = 
			new BYTE();

	@XmlTransient
	public WORD getTimeYear()
	{
		 return this.timeYear;
	}

	public void setTimeYear(WORD timeYear)
	{
		 this.timeYear=timeYear;
	}

	@XmlTransient
	public BYTE getTimeMon()
	{
		 return this.timeMon;
	}

	public void setTimeMon(BYTE timeMon)
	{
		 this.timeMon=timeMon;
	}

	@XmlTransient
	public BYTE getTimeDay()
	{
		 return this.timeDay;
	}

	public void setTimeDay(BYTE timeDay)
	{
		 this.timeDay=timeDay;
	}

	@XmlTransient
	public BYTE getTimeHour()
	{
		 return this.timeHour;
	}

	public void setTimeHour(BYTE timeHour)
	{
		 this.timeHour=timeHour;
	}

	@XmlTransient
	public BYTE getTimeMin()
	{
		 return this.timeMin;
	}

	public void setTimeMin(BYTE timeMin)
	{
		 this.timeMin=timeMin;
	}

	@XmlTransient
	public BYTE getTimeSec()
	{
		 return this.timeSec;
	}

	public void setTimeSec(BYTE timeSec)
	{
		 this.timeSec=timeSec;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("timeYear: " + timeYear + "\n");
		sb.append("timeMon: " + timeMon + "\n");
		sb.append("timeDay: " + timeDay + "\n");
		sb.append("timeHour: " + timeHour + "\n");
		sb.append("timeMin: " + timeMin + "\n");
		sb.append("timeSec: " + timeSec + "\n");


        return sb.toString();
    }
}
