package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * sensorPageEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class sensorPageEntry extends Entry {

	public OCTET sensorPage1 = 
			new OCTET();

	public OCTET sensorPage2 = 
			new OCTET();

	public OCTET sensorPage3 = 
			new OCTET();

	public OCTET sensorPage4 = 
			new OCTET();

	public OCTET sensorPage5 = 
			new OCTET();

	public OCTET sensorPage6 = 
			new OCTET();

	public OCTET sensorPage7 = 
			new OCTET();

	public OCTET sensorPage8 = 
			new OCTET();

	public OCTET sensorPage9 = 
			new OCTET();

	public OCTET sensorPage10 = 
			new OCTET();

	public OCTET sensorPage11 = 
			new OCTET();

	public OCTET sensorPage12 = 
			new OCTET();

	public OCTET sensorPage13 = 
			new OCTET();

	public OCTET sensorPage14 = 
			new OCTET();

	public OCTET sensorPage15 = 
			new OCTET();

	public OCTET sensorPage16 = 
			new OCTET();

	public OCTET sensorPage17 = 
			new OCTET();

	public OCTET sensorPage18 = 
			new OCTET();

	public OCTET sensorPage19 = 
			new OCTET();

	public OCTET sensorPage20 = 
			new OCTET();

	public OCTET sensorPage21 = 
			new OCTET();

	public OCTET sensorPage22 = 
			new OCTET();

	public OCTET sensorPage23 = 
			new OCTET();

	public OCTET sensorPage24 = 
			new OCTET();

	public OCTET sensorPage25 = 
			new OCTET();

	public OCTET sensorPage26 = 
			new OCTET();

	public OCTET sensorPage27 = 
			new OCTET();

	public OCTET sensorPage28 = 
			new OCTET();

	public OCTET sensorPage29 = 
			new OCTET();

	public OCTET sensorPage30 = 
			new OCTET();

	public OCTET sensorPage31 = 
			new OCTET();

	public OCTET sensorPage32 = 
			new OCTET();

	public OCTET sensorPage33 = 
			new OCTET();

	public OCTET sensorPage34 = 
			new OCTET();

	public OCTET sensorPage35 = 
			new OCTET();

	public OCTET sensorPage36 = 
			new OCTET();

	public OCTET sensorPage37 = 
			new OCTET();

	public OCTET sensorPage38 = 
			new OCTET();

	public OCTET sensorPage39 = 
			new OCTET();

	public OCTET sensorPage40 = 
			new OCTET();

	@XmlTransient
	public OCTET getSensorPage1()
	{
		 return this.sensorPage1;
	}

	public void setSensorPage1(OCTET sensorPage1)
	{
		 this.sensorPage1=sensorPage1;
	}

	@XmlTransient
	public OCTET getSensorPage2()
	{
		 return this.sensorPage2;
	}

	public void setSensorPage2(OCTET sensorPage2)
	{
		 this.sensorPage2=sensorPage2;
	}

	@XmlTransient
	public OCTET getSensorPage3()
	{
		 return this.sensorPage3;
	}

	public void setSensorPage3(OCTET sensorPage3)
	{
		 this.sensorPage3=sensorPage3;
	}

	@XmlTransient
	public OCTET getSensorPage4()
	{
		 return this.sensorPage4;
	}

	public void setSensorPage4(OCTET sensorPage4)
	{
		 this.sensorPage4=sensorPage4;
	}

	@XmlTransient
	public OCTET getSensorPage5()
	{
		 return this.sensorPage5;
	}

	public void setSensorPage5(OCTET sensorPage5)
	{
		 this.sensorPage5=sensorPage5;
	}

	@XmlTransient
	public OCTET getSensorPage6()
	{
		 return this.sensorPage6;
	}

	public void setSensorPage6(OCTET sensorPage6)
	{
		 this.sensorPage6=sensorPage6;
	}

	@XmlTransient
	public OCTET getSensorPage7()
	{
		 return this.sensorPage7;
	}

	public void setSensorPage7(OCTET sensorPage7)
	{
		 this.sensorPage7=sensorPage7;
	}

	@XmlTransient
	public OCTET getSensorPage8()
	{
		 return this.sensorPage8;
	}

	public void setSensorPage8(OCTET sensorPage8)
	{
		 this.sensorPage8=sensorPage8;
	}

	@XmlTransient
	public OCTET getSensorPage9()
	{
		 return this.sensorPage9;
	}

	public void setSensorPage9(OCTET sensorPage9)
	{
		 this.sensorPage9=sensorPage9;
	}

	@XmlTransient
	public OCTET getSensorPage10()
	{
		 return this.sensorPage10;
	}

	public void setSensorPage10(OCTET sensorPage10)
	{
		 this.sensorPage10=sensorPage10;
	}

	@XmlTransient
	public OCTET getSensorPage11()
	{
		 return this.sensorPage11;
	}

	public void setSensorPage11(OCTET sensorPage11)
	{
		 this.sensorPage11=sensorPage11;
	}

	@XmlTransient
	public OCTET getSensorPage12()
	{
		 return this.sensorPage12;
	}

	public void setSensorPage12(OCTET sensorPage12)
	{
		 this.sensorPage12=sensorPage12;
	}

	@XmlTransient
	public OCTET getSensorPage13()
	{
		 return this.sensorPage13;
	}

	public void setSensorPage13(OCTET sensorPage13)
	{
		 this.sensorPage13=sensorPage13;
	}

	@XmlTransient
	public OCTET getSensorPage14()
	{
		 return this.sensorPage14;
	}

	public void setSensorPage14(OCTET sensorPage14)
	{
		 this.sensorPage14=sensorPage14;
	}

	@XmlTransient
	public OCTET getSensorPage15()
	{
		 return this.sensorPage15;
	}

	public void setSensorPage15(OCTET sensorPage15)
	{
		 this.sensorPage15=sensorPage15;
	}

	@XmlTransient
	public OCTET getSensorPage16()
	{
		 return this.sensorPage16;
	}

	public void setSensorPage16(OCTET sensorPage16)
	{
		 this.sensorPage16=sensorPage16;
	}

	@XmlTransient
	public OCTET getSensorPage17()
	{
		 return this.sensorPage17;
	}

	public void setSensorPage17(OCTET sensorPage17)
	{
		 this.sensorPage17=sensorPage17;
	}

	@XmlTransient
	public OCTET getSensorPage18()
	{
		 return this.sensorPage18;
	}

	public void setSensorPage18(OCTET sensorPage18)
	{
		 this.sensorPage18=sensorPage18;
	}

	@XmlTransient
	public OCTET getSensorPage19()
	{
		 return this.sensorPage19;
	}

	public void setSensorPage19(OCTET sensorPage19)
	{
		 this.sensorPage19=sensorPage19;
	}

	@XmlTransient
	public OCTET getSensorPage20()
	{
		 return this.sensorPage20;
	}

	public void setSensorPage20(OCTET sensorPage20)
	{
		 this.sensorPage20=sensorPage20;
	}

	@XmlTransient
	public OCTET getSensorPage21()
	{
		 return this.sensorPage21;
	}

	public void setSensorPage21(OCTET sensorPage21)
	{
		 this.sensorPage21=sensorPage21;
	}

	@XmlTransient
	public OCTET getSensorPage22()
	{
		 return this.sensorPage22;
	}

	public void setSensorPage22(OCTET sensorPage22)
	{
		 this.sensorPage22=sensorPage22;
	}

	@XmlTransient
	public OCTET getSensorPage23()
	{
		 return this.sensorPage23;
	}

	public void setSensorPage23(OCTET sensorPage23)
	{
		 this.sensorPage23=sensorPage23;
	}

	@XmlTransient
	public OCTET getSensorPage24()
	{
		 return this.sensorPage24;
	}

	public void setSensorPage24(OCTET sensorPage24)
	{
		 this.sensorPage24=sensorPage24;
	}

	@XmlTransient
	public OCTET getSensorPage25()
	{
		 return this.sensorPage25;
	}

	public void setSensorPage25(OCTET sensorPage25)
	{
		 this.sensorPage25=sensorPage25;
	}

	@XmlTransient
	public OCTET getSensorPage26()
	{
		 return this.sensorPage26;
	}

	public void setSensorPage26(OCTET sensorPage26)
	{
		 this.sensorPage26=sensorPage26;
	}

	@XmlTransient
	public OCTET getSensorPage27()
	{
		 return this.sensorPage27;
	}

	public void setSensorPage27(OCTET sensorPage27)
	{
		 this.sensorPage27=sensorPage27;
	}

	@XmlTransient
	public OCTET getSensorPage28()
	{
		 return this.sensorPage28;
	}

	public void setSensorPage28(OCTET sensorPage28)
	{
		 this.sensorPage28=sensorPage28;
	}

	@XmlTransient
	public OCTET getSensorPage29()
	{
		 return this.sensorPage29;
	}

	public void setSensorPage29(OCTET sensorPage29)
	{
		 this.sensorPage29=sensorPage29;
	}

	@XmlTransient
	public OCTET getSensorPage30()
	{
		 return this.sensorPage30;
	}

	public void setSensorPage30(OCTET sensorPage30)
	{
		 this.sensorPage30=sensorPage30;
	}

	@XmlTransient
	public OCTET getSensorPage31()
	{
		 return this.sensorPage31;
	}

	public void setSensorPage31(OCTET sensorPage31)
	{
		 this.sensorPage31=sensorPage31;
	}

	@XmlTransient
	public OCTET getSensorPage32()
	{
		 return this.sensorPage32;
	}

	public void setSensorPage32(OCTET sensorPage32)
	{
		 this.sensorPage32=sensorPage32;
	}

	@XmlTransient
	public OCTET getSensorPage33()
	{
		 return this.sensorPage33;
	}

	public void setSensorPage33(OCTET sensorPage33)
	{
		 this.sensorPage33=sensorPage33;
	}

	@XmlTransient
	public OCTET getSensorPage34()
	{
		 return this.sensorPage34;
	}

	public void setSensorPage34(OCTET sensorPage34)
	{
		 this.sensorPage34=sensorPage34;
	}

	@XmlTransient
	public OCTET getSensorPage35()
	{
		 return this.sensorPage35;
	}

	public void setSensorPage35(OCTET sensorPage35)
	{
		 this.sensorPage35=sensorPage35;
	}

	@XmlTransient
	public OCTET getSensorPage36()
	{
		 return this.sensorPage36;
	}

	public void setSensorPage36(OCTET sensorPage36)
	{
		 this.sensorPage36=sensorPage36;
	}

	@XmlTransient
	public OCTET getSensorPage37()
	{
		 return this.sensorPage37;
	}

	public void setSensorPage37(OCTET sensorPage37)
	{
		 this.sensorPage37=sensorPage37;
	}

	@XmlTransient
	public OCTET getSensorPage38()
	{
		 return this.sensorPage38;
	}

	public void setSensorPage38(OCTET sensorPage38)
	{
		 this.sensorPage38=sensorPage38;
	}

	@XmlTransient
	public OCTET getSensorPage39()
	{
		 return this.sensorPage39;
	}

	public void setSensorPage39(OCTET sensorPage39)
	{
		 this.sensorPage39=sensorPage39;
	}

	@XmlTransient
	public OCTET getSensorPage40()
	{
		 return this.sensorPage40;
	}

	public void setSensorPage40(OCTET sensorPage40)
	{
		 this.sensorPage40=sensorPage40;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("sensorPage1: " + sensorPage1 + "\n");
		sb.append("sensorPage2: " + sensorPage2 + "\n");
		sb.append("sensorPage3: " + sensorPage3 + "\n");
		sb.append("sensorPage4: " + sensorPage4 + "\n");
		sb.append("sensorPage5: " + sensorPage5 + "\n");
		sb.append("sensorPage6: " + sensorPage6 + "\n");
		sb.append("sensorPage7: " + sensorPage7 + "\n");
		sb.append("sensorPage8: " + sensorPage8 + "\n");
		sb.append("sensorPage9: " + sensorPage9 + "\n");
		sb.append("sensorPage10: " + sensorPage10 + "\n");
		sb.append("sensorPage11: " + sensorPage11 + "\n");
		sb.append("sensorPage12: " + sensorPage12 + "\n");
		sb.append("sensorPage13: " + sensorPage13 + "\n");
		sb.append("sensorPage14: " + sensorPage14 + "\n");
		sb.append("sensorPage15: " + sensorPage15 + "\n");
		sb.append("sensorPage16: " + sensorPage16 + "\n");
		sb.append("sensorPage17: " + sensorPage17 + "\n");
		sb.append("sensorPage18: " + sensorPage18 + "\n");
		sb.append("sensorPage19: " + sensorPage19 + "\n");
		sb.append("sensorPage20: " + sensorPage20 + "\n");
		sb.append("sensorPage21: " + sensorPage21 + "\n");
		sb.append("sensorPage22: " + sensorPage22 + "\n");
		sb.append("sensorPage23: " + sensorPage23 + "\n");
		sb.append("sensorPage24: " + sensorPage24 + "\n");
		sb.append("sensorPage25: " + sensorPage25 + "\n");
		sb.append("sensorPage26: " + sensorPage26 + "\n");
		sb.append("sensorPage27: " + sensorPage27 + "\n");
		sb.append("sensorPage28: " + sensorPage28 + "\n");
		sb.append("sensorPage29: " + sensorPage29 + "\n");
		sb.append("sensorPage30: " + sensorPage30 + "\n");
		sb.append("sensorPage31: " + sensorPage31 + "\n");
		sb.append("sensorPage32: " + sensorPage32 + "\n");
		sb.append("sensorPage33: " + sensorPage33 + "\n");
		sb.append("sensorPage34: " + sensorPage34 + "\n");
		sb.append("sensorPage35: " + sensorPage35 + "\n");
		sb.append("sensorPage36: " + sensorPage36 + "\n");
		sb.append("sensorPage37: " + sensorPage37 + "\n");
		sb.append("sensorPage38: " + sensorPage38 + "\n");
		sb.append("sensorPage39: " + sensorPage39 + "\n");
		sb.append("sensorPage40: " + sensorPage40 + "\n");


        return sb.toString();
    }
}
