package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * mobileEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 * <pre>
 * &lt;complexType name="mobileEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{http://server.ws.command.fep.aimir.com/}entry">
 *       &lt;sequence>
 *         &lt;element name="mobileID" type="{http://server.ws.command.fep.aimir.com/}octet" minOccurs="0"/>
 *         &lt;element name="mobileIpaddr" type="{http://server.ws.command.fep.aimir.com/}ipaddr" minOccurs="0"/>
 *         &lt;element name="mobileRxDbm" type="{http://server.ws.command.fep.aimir.com/}int" minOccurs="0"/>
 *         &lt;element name="mobileTxDbm" type="{http://server.ws.command.fep.aimir.com/}int" minOccurs="0"/>
 *         &lt;element name="mobilePacketLiveTime" type="{http://server.ws.command.fep.aimir.com/}uint" minOccurs="0"/>
 *         &lt;element name="mobileSendBytes" type="{http://server.ws.command.fep.aimir.com/}uint" minOccurs="0"/>
 *         &lt;element name="mobileRecvBytes" type="{http://server.ws.command.fep.aimir.com/}uint" minOccurs="0"/>
 *         &lt;element name="mobileLastConnectTime" type="{http://server.ws.command.fep.aimir.com/}timestamp" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mobileEntry", propOrder = {
    "mobileID",
    "mobileIpaddr",
    "mobileRxDbm",
    "mobileTxDbm",
    "mobilePacketLiveTime",
    "mobileSendBytes",
    "mobileRecvBytes",
    "mobileLastConnectTime"
})
public class mobileEntry extends Entry {

	public OCTET mobileID = 
			new OCTET(16);

	public IPADDR mobileIpaddr = 
			new IPADDR();

	public INT mobileRxDbm = 
			new INT();

	public INT mobileTxDbm = 
			new INT();

	public UINT mobilePacketLiveTime = 
			new UINT();

	public UINT mobileSendBytes = 
			new UINT();

	public UINT mobileRecvBytes = 
			new UINT();

	public TIMESTAMP mobileLastConnectTime = 
			new TIMESTAMP(7);

	@XmlTransient
	public OCTET getMobileID()
	{
		 return this.mobileID;
	}

	public void setMobileID(OCTET mobileID)
	{
		 this.mobileID=mobileID;
	}

	@XmlTransient
	public IPADDR getMobileIpaddr()
	{
		 return this.mobileIpaddr;
	}

	public void setMobileIpaddr(IPADDR mobileIpaddr)
	{
		 this.mobileIpaddr=mobileIpaddr;
	}

	@XmlTransient
	public INT getMobileRxDbm()
	{
		 return this.mobileRxDbm;
	}

	public void setMobileRxDbm(INT mobileRxDbm)
	{
		 this.mobileRxDbm=mobileRxDbm;
	}

	@XmlTransient
	public INT getMobileTxDbm()
	{
		 return this.mobileTxDbm;
	}

	public void setMobileTxDbm(INT mobileTxDbm)
	{
		 this.mobileTxDbm=mobileTxDbm;
	}

	@XmlTransient
	public UINT getMobilePacketLiveTime()
	{
		 return this.mobilePacketLiveTime;
	}

	public void setMobilePacketLiveTime(UINT mobilePacketLiveTime)
	{
		 this.mobilePacketLiveTime=mobilePacketLiveTime;
	}

	@XmlTransient
	public UINT getMobileSendBytes()
	{
		 return this.mobileSendBytes;
	}

	public void setMobileSendBytes(UINT mobileSendBytes)
	{
		 this.mobileSendBytes=mobileSendBytes;
	}

	@XmlTransient
	public UINT getMobileRecvBytes()
	{
		 return this.mobileRecvBytes;
	}

	public void setMobileRecvBytes(UINT mobileRecvBytes)
	{
		 this.mobileRecvBytes=mobileRecvBytes;
	}

	@XmlTransient
	public TIMESTAMP getMobileLastConnectTime()
	{
		 return this.mobileLastConnectTime;
	}

	public void setMobileLastConnectTime(TIMESTAMP mobileLastConnectTime)
	{
		 this.mobileLastConnectTime=mobileLastConnectTime;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("mobileID: " + mobileID + "\n");
		sb.append("mobileIpaddr: " + mobileIpaddr + "\n");
		sb.append("mobileRxDbm: " + mobileRxDbm + "\n");
		sb.append("mobileTxDbm: " + mobileTxDbm + "\n");
		sb.append("mobilePacketLiveTime: " + mobilePacketLiveTime + "\n");
		sb.append("mobileSendBytes: " + mobileSendBytes + "\n");
		sb.append("mobileRecvBytes: " + mobileRecvBytes + "\n");
		sb.append("mobileLastConnectTime: " + mobileLastConnectTime + "\n");


        return sb.toString();
    }
}
