package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * usrEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class usrEntry extends Entry {

	public BYTE usrMask = 
			new BYTE();

	public OCTET usrAccount = 
			new OCTET(16);

	public OCTET usrPassword = 
			new OCTET(16);

	public BYTE usrGroup = 
			new BYTE();

	@XmlTransient
	public BYTE getUsrMask()
	{
		 return this.usrMask;
	}

	public void setUsrMask(BYTE usrMask)
	{
		 this.usrMask=usrMask;
	}

	@XmlTransient
	public OCTET getUsrAccount()
	{
		 return this.usrAccount;
	}

	public void setUsrAccount(OCTET usrAccount)
	{
		 this.usrAccount=usrAccount;
	}

	@XmlTransient
	public OCTET getUsrPassword()
	{
		 return this.usrPassword;
	}

	public void setUsrPassword(OCTET usrPassword)
	{
		 this.usrPassword=usrPassword;
	}

	@XmlTransient
	public BYTE getUsrGroup()
	{
		 return this.usrGroup;
	}

	public void setUsrGroup(BYTE usrGroup)
	{
		 this.usrGroup=usrGroup;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("usrMask: " + usrMask + "\n");
		sb.append("usrAccount: " + usrAccount + "\n");
		sb.append("usrPassword: " + usrPassword + "\n");
		sb.append("usrGroup: " + usrGroup + "\n");


        return sb.toString();
    }
}
