package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * meterEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class meterEntry extends Entry {

	public BYTE mtrGroup = 
			new BYTE();

	public BYTE mtrMember = 
			new BYTE();

	public HEX mtrID = 
			new HEX(8);

	public OCTET mtrSerial = 
			new OCTET(18);

	public TIMESTAMP mtrTime = 
			new TIMESTAMP(7);

	public OCTET mtrData = 
			new OCTET();

	@XmlTransient
	public BYTE getMtrGroup()
	{
		 return this.mtrGroup;
	}

	public void setMtrGroup(BYTE mtrGroup)
	{
		 this.mtrGroup=mtrGroup;
	}

	@XmlTransient
	public BYTE getMtrMember()
	{
		 return this.mtrMember;
	}

	public void setMtrMember(BYTE mtrMember)
	{
		 this.mtrMember=mtrMember;
	}

	@XmlTransient
	public HEX getMtrID()
	{
		 return this.mtrID;
	}

	public void setMtrID(HEX mtrID)
	{
		 this.mtrID=mtrID;
	}

	@XmlTransient
	public OCTET getMtrSerial()
	{
		 return this.mtrSerial;
	}

	public void setMtrSerial(OCTET mtrSerial)
	{
		 this.mtrSerial=mtrSerial;
	}

	@XmlTransient
	public TIMESTAMP getMtrTime()
	{
		 return this.mtrTime;
	}

	public void setMtrTime(TIMESTAMP mtrTime)
	{
		 this.mtrTime=mtrTime;
	}

	@XmlTransient
	public OCTET getMtrData()
	{
		 return this.mtrData;
	}

	public void setMtrData(OCTET mtrData)
	{
		 this.mtrData=mtrData;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("mtrGroup: " + mtrGroup + "\n");
		sb.append("mtrMember: " + mtrMember + "\n");
		sb.append("mtrID: " + mtrID + "\n");
		sb.append("mtrSerial: " + mtrSerial + "\n");
		sb.append("mtrTime: " + mtrTime + "\n");
		sb.append("mtrData: " + mtrData.toHexString() + "\n");


        return sb.toString();
    }
}
