package com.aimir.cms.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-01-11T13:33:56.695+09:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "CmsWS", 
                  wsdlLocation = "http://localhost:8081/services/CmsWS?wsdl",
                  targetNamespace = "http://server.ws.cms.aimir.com/") 
public class CmsWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.ws.cms.aimir.com/", "CmsWS");
    public final static QName CmsWSPort = new QName("http://server.ws.cms.aimir.com/", "CmsWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/services/CmsWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CmsWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/services/CmsdWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CmsWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CmsWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmsWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CmsWS
     */
    @WebEndpoint(name = "CmsWSPort")
    public CmsWS getCmsWSPort() {
        return super.getPort(CmsWSPort, CmsWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmsWS
     */
    @WebEndpoint(name = "CmsWSPort")
    public CmsWS getCmsWSPort(WebServiceFeature... features) {
        return super.getPort(CmsWSPort, CmsWS.class, features);
    }

}
