package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.aimir.fep.protocol.fmp.datatype.BYTE;
import com.aimir.fep.protocol.fmp.datatype.OCTET;
import com.aimir.fep.protocol.fmp.datatype.WORD;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * cmdHistStruct
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cmdHistStruct", propOrder = {
        "cmdHistLength",
        "cmdHistTimeHour",
        "cmdHistTimeMin",
        "cmdHistTimeSec",
        "cmdHistOwner",
        "cmdHistUser",
        "cmdHistData"
})
public class cmdHistStruct extends Entry {

	public WORD cmdHistLength = 
			new WORD();

	public BYTE cmdHistTimeHour = 
			new BYTE();

	public BYTE cmdHistTimeMin = 
			new BYTE();

	public BYTE cmdHistTimeSec = 
			new BYTE();

	public BYTE cmdHistOwner = 
			new BYTE();

	public OCTET cmdHistUser = 
			new OCTET(16);

	public OCTET cmdHistData = 
			new OCTET();

	@XmlTransient
	public WORD getCmdHistLength()
	{
		 return this.cmdHistLength;
	}

	public void setCmdHistLength(WORD cmdHistLength)
	{
		 this.cmdHistLength=cmdHistLength;
	}

	@XmlTransient
	public BYTE getCmdHistTimeHour()
	{
		 return this.cmdHistTimeHour;
	}

	public void setCmdHistTimeHour(BYTE cmdHistTimeHour)
	{
		 this.cmdHistTimeHour=cmdHistTimeHour;
	}

	@XmlTransient
	public BYTE getCmdHistTimeMin()
	{
		 return this.cmdHistTimeMin;
	}

	public void setCmdHistTimeMin(BYTE cmdHistTimeMin)
	{
		 this.cmdHistTimeMin=cmdHistTimeMin;
	}

	@XmlTransient
	public BYTE getCmdHistTimeSec()
	{
		 return this.cmdHistTimeSec;
	}

	public void setCmdHistTimeSec(BYTE cmdHistTimeSec)
	{
		 this.cmdHistTimeSec=cmdHistTimeSec;
	}

	@XmlTransient
	public BYTE getCmdHistOwner()
	{
		 return this.cmdHistOwner;
	}

	public void setCmdHistOwner(BYTE cmdHistOwner)
	{
		 this.cmdHistOwner=cmdHistOwner;
	}

	@XmlTransient
	public OCTET getCmdHistUser()
	{
		 return this.cmdHistUser;
	}

	public void setCmdHistUser(OCTET cmdHistUser)
	{
		 this.cmdHistUser=cmdHistUser;
	}

	@XmlTransient
	public OCTET getCmdHistData()
	{
		 return this.cmdHistData;
	}

	public void setCmdHistData(OCTET cmdHistData)
	{
		 this.cmdHistData=cmdHistData;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("cmdHistLength: " + cmdHistLength + "\n");
		sb.append("cmdHistTimeHour: " + cmdHistTimeHour + "\n");
		sb.append("cmdHistTimeMin: " + cmdHistTimeMin + "\n");
		sb.append("cmdHistTimeSec: " + cmdHistTimeSec + "\n");
		sb.append("cmdHistOwner: " + cmdHistOwner + "\n");
		sb.append("cmdHistUser: " + cmdHistUser + "\n");
		sb.append("cmdHistData: " + cmdHistData + "\n");


        return sb.toString();
    }
}
