package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * codiNeighborEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2007-10-03 15:59:15 +0900 $,
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="codiNeighborEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{http://server.ws.command.fep.aimir.com/}entry">
 *       &lt;sequence>
 *         &lt;element name="codiNeighborIndex" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="codiNeighborShortID" type="{http://server.ws.command.fep.aimir.com/}word" minOccurs="0"/>
 *         &lt;element name="codiNeighborLqi" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="codiNeighborInCost" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="codiNeighborOutCost" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="codiNeighborAge" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="codiNeighborID" type="{http://server.ws.command.fep.aimir.com/}hex" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "codiNeighborEntry", propOrder = {
    "codiNeighborIndex",
    "codiNeighborShortID",
    "codiNeighborLqi",
    "codiNeighborInCost",
    "codiNeighborOutCost",
    "codiNeighborAge",
    "codiNeighborID"
})
public class codiNeighborEntry extends Entry {
    public BYTE codiNeighborIndex = 
            new BYTE();
    public WORD codiNeighborShortID = 
            new WORD();
    public BYTE codiNeighborLqi = 
            new BYTE();
    public BYTE codiNeighborInCost = 
            new BYTE();
    public BYTE codiNeighborOutCost = 
            new BYTE();
    public BYTE codiNeighborAge = 
            new BYTE();    
    public HEX codiNeighborID = 
            new HEX(8);

    @XmlTransient
    public BYTE getCodiNeighborIndex()
    {
        return this.codiNeighborIndex;
    } 

    public void setCodiNeighborIndex(BYTE codiNeighborIndex)
    {
        this.codiNeighborIndex = codiNeighborIndex;
    }

    @XmlTransient
    public WORD getCodiNeighborShortID()
    {
        return this.codiNeighborShortID;
    } 

    public void setCodiNeighborShortID(WORD codiNeighborShortID)
    {
        this.codiNeighborShortID = codiNeighborShortID;
    }
    
    @XmlTransient
    public BYTE getCodiNeighborLqi()
    {
        return this.codiNeighborLqi;
    } 

    public void setCodiNeighborLqi(BYTE codiNeighborLqi)
    {
        this.codiNeighborLqi = codiNeighborLqi;
    }

    @XmlTransient
    public BYTE getCodiNeighborInCost()
    {
        return this.codiNeighborInCost;
    } 

    public void setCodiNeighborInCost(BYTE codiNeighborInCost)
    {
        this.codiNeighborInCost = codiNeighborInCost;
    }

    @XmlTransient
    public BYTE getCodiNeighborOutCost()
    {
        return this.codiNeighborOutCost;
    } 

    public void setCodiNeighborOutCost(BYTE codiNeighborOutCost)
    {
        this.codiNeighborOutCost = codiNeighborOutCost;
    }
    
    @XmlTransient
    public BYTE getCodiNeighborAge()
    {
        return this.codiNeighborAge;
    } 

    public void setCodiNeighborAge(BYTE codiNeighborAge)
    {
        this.codiNeighborAge = codiNeighborAge;
    }
    
    @XmlTransient
    public HEX getCodiNeighborID()
    {
        return this.codiNeighborID;
    } 

    public void setCodiNeighborID(HEX codiNeighborID)
    {
        this.codiNeighborID = codiNeighborID;
    }

    public String toString()
    {
        StringBuffer sb = new StringBuffer();

        sb.append("CLASS["+this.getClass().getName()+"]\n");
        sb.append("codiNeighborIndex: " + codiNeighborIndex + "\n");
        sb.append("codiNeighborShortID: " + codiNeighborShortID + "\n");
        sb.append("codiNeighborLqi: " + codiNeighborLqi + "\n");
        sb.append("codiNeighborInCost: " + codiNeighborInCost + "\n");
        sb.append("codiNeighborOutCost: " + codiNeighborOutCost + "\n");
        sb.append("codiNeighborAge: " + codiNeighborAge + "\n");
        sb.append("codiNeighborID: " + codiNeighborID + "\n");

        return sb.toString();
    }
}
