package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * dayEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class dayEntry extends Entry {

	public WORD dayYear = 
			new WORD();

	public BYTE dayMon = 
			new BYTE();

	public BYTE dayDay = 
			new BYTE();

	@XmlTransient
	public WORD getDayYear()
	{
		 return this.dayYear;
	}

	public void setDayYear(WORD dayYear)
	{
		 this.dayYear=dayYear;
	}

	@XmlTransient
	public BYTE getDayMon()
	{
		 return this.dayMon;
	}

	public void setDayMon(BYTE dayMon)
	{
		 this.dayMon=dayMon;
	}

	@XmlTransient
	public BYTE getDayDay()
	{
		 return this.dayDay;
	}

	public void setDayDay(BYTE dayDay)
	{
		 this.dayDay=dayDay;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("dayYear: " + dayYear + "\n");
		sb.append("dayMon: " + dayMon + "\n");
		sb.append("dayDay: " + dayDay + "\n");


        return sb.toString();
    }
}
