package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * mcuEventStruct
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class mcuEventStruct extends Entry {

	public WORD mcuEventLength = 
			new WORD();

	public OCTET mcuEventData = 
			new OCTET();

	@XmlTransient
	public WORD getMcuEventLength()
	{
		 return this.mcuEventLength;
	}

	public void setMcuEventLength(WORD mcuEventLength)
	{
		 this.mcuEventLength=mcuEventLength;
	}

	@XmlTransient
	public OCTET getMcuEventData()
	{
		 return this.mcuEventData;
	}

	public void setMcuEventData(OCTET mcuEventData)
	{
		 this.mcuEventData=mcuEventData;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("mcuEventLength: " + mcuEventLength + "\n");
		sb.append("mcuEventData: " + mcuEventData + "\n");


        return sb.toString();
    }
}
