package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * memEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 * <pre>
 * &lt;complexType name="memEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{http://server.ws.command.fep.aimir.com/}entry">
 *       &lt;sequence>
 *         &lt;element name="memTotalSize" type="{http://server.ws.command.fep.aimir.com/}uint" minOccurs="0"/>
 *         &lt;element name="memFreeSize" type="{http://server.ws.command.fep.aimir.com/}uint" minOccurs="0"/>
 *         &lt;element name="memUseSize" type="{http://server.ws.command.fep.aimir.com/}uint" minOccurs="0"/>
 *         &lt;element name="memCacheSize" type="{http://server.ws.command.fep.aimir.com/}uint" minOccurs="0"/>
 *         &lt;element name="memBufferSize" type="{http://server.ws.command.fep.aimir.com/}uint" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "memEntry", propOrder = {
    "memTotalSize",
    "memFreeSize",
    "memUseSize",
    "memCacheSize",
    "memBufferSize"
})
public class memEntry extends Entry {

	public UINT memTotalSize = 
			new UINT();

	public UINT memFreeSize = 
			new UINT();

	public UINT memUseSize = 
			new UINT();

	public UINT memCacheSize = 
			new UINT();

	public UINT memBufferSize = 
			new UINT();

	@XmlTransient
	public UINT getMemTotalSize()
	{
		 return this.memTotalSize;
	}

	public void setMemTotalSize(UINT memTotalSize)
	{
		 this.memTotalSize=memTotalSize;
	}

	@XmlTransient
	public UINT getMemFreeSize()
	{
		 return this.memFreeSize;
	}

	public void setMemFreeSize(UINT memFreeSize)
	{
		 this.memFreeSize=memFreeSize;
	}

	@XmlTransient
	public UINT getMemUseSize()
	{
		 return this.memUseSize;
	}

	public void setMemUseSize(UINT memUseSize)
	{
		 this.memUseSize=memUseSize;
	}

	@XmlTransient
	public UINT getMemCacheSize()
	{
		 return this.memCacheSize;
	}

	public void setMemCacheSize(UINT memCacheSize)
	{
		 this.memCacheSize=memCacheSize;
	}

	@XmlTransient
	public UINT getMemBufferSize()
	{
		 return this.memBufferSize;
	}

	public void setMemBufferSize(UINT memBufferSize)
	{
		 this.memBufferSize=memBufferSize;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("memTotalSize: " + memTotalSize + "\n");
		sb.append("memFreeSize: " + memFreeSize + "\n");
		sb.append("memUseSize: " + memUseSize + "\n");
		sb.append("memCacheSize: " + memCacheSize + "\n");
		sb.append("memBufferSize: " + memBufferSize + "\n");


        return sb.toString();
    }
}
