package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * meterLogEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class meterLogEntry extends Entry {

	public TIMESTAMP meterLogDate = 
			new TIMESTAMP(7);

	public OCTET meterLogFileName = 
			new OCTET(32);

	public UINT meterLogFileSize = 
			new UINT();

	@XmlTransient
	public TIMESTAMP getMeterLogDate()
	{
		 return this.meterLogDate;
	}

	public void setMeterLogDate(TIMESTAMP meterLogDate)
	{
		 this.meterLogDate=meterLogDate;
	}

	@XmlTransient
	public OCTET getMeterLogFileName()
	{
		 return this.meterLogFileName;
	}

	public void setMeterLogFileName(OCTET meterLogFileName)
	{
		 this.meterLogFileName=meterLogFileName;
	}

	@XmlTransient
	public UINT getMeterLogFileSize()
	{
		 return this.meterLogFileSize;
	}

	public void setMeterLogFileSize(UINT meterLogFileSize)
	{
		 this.meterLogFileSize=meterLogFileSize;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("meterLogDate: " + meterLogDate + "\n");
		sb.append("meterLogFileName: " + meterLogFileName + "\n");
		sb.append("meterLogFileSize: " + meterLogFileSize + "\n");


        return sb.toString();
    }
}
