package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.BOOL;
import com.aimir.fep.protocol.fmp.datatype.BYTE;
import com.aimir.fep.protocol.fmp.datatype.HEX;
import com.aimir.fep.protocol.fmp.datatype.INT;
import com.aimir.fep.protocol.fmp.datatype.OCTET;
import com.aimir.fep.protocol.fmp.datatype.TIMESTAMP;
import com.aimir.fep.protocol.fmp.datatype.WORD;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * meterDataEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class meterDataEntry2 extends Entry {
	
    public OCTET meterId = new OCTET(20);
    
    public OCTET meterModel = new OCTET(20);
    
    public OCTET meterVendor = new OCTET(3);
   
    public BYTE type = new BYTE(1);
    
    public BYTE meterPhase = new BYTE(1);
    
    public HEX meterModemId = new HEX(8);
      
    public WORD shortId = new WORD(2);
    
    public BOOL status = new BOOL();
    
    public TIMESTAMP installTime = new TIMESTAMP(7);
    
    public TIMESTAMP lastOnLine = new TIMESTAMP(7);
    
    public TIMESTAMP lastOffLine = new TIMESTAMP(7);
    
    public INT failReason = new INT(4);
    
    public TIMESTAMP billingTime = new TIMESTAMP(7);
    
    public BYTE relayStatus = new BYTE(1);
    
    @XmlTransient
    public OCTET getMeterId() {
		return meterId;
	}

	public void setMeterId(OCTET meterId) {
		this.meterId = meterId;
	}
	
	@XmlTransient
	public OCTET getMeterModel() {
		return meterModel;
	}

	public void setMeterModel(OCTET meterModel) {
		this.meterModel = meterModel;
	}

	@XmlTransient
	public OCTET getMeterVendor() {
		return meterVendor;
	}

	public void setMeterVendor(OCTET meterVendor) {
		this.meterVendor = meterVendor;
	}

	@XmlTransient
	public BYTE getType() {
		return type;
	}

	public void setType(BYTE type) {
		this.type = type;
	}

	@XmlTransient
	public BYTE getMeterPhase() {
		return meterPhase;
	}

	public void setMeterPhase(BYTE meterPhase) {
		this.meterPhase = meterPhase;
	}

	@XmlTransient
	public WORD getShortId() {
		return shortId;
	}

	public void setShortId(WORD shortId) {
		this.shortId = shortId;
	}

	@XmlTransient
	public BOOL getStatus() {
		return status;
	}

	public void setStatus(BOOL status) {
		this.status = status;
	}

	@XmlTransient
	public TIMESTAMP getInstallTime() {
		return installTime;
	}

	public void setInstallTime(TIMESTAMP installTime) {
		this.installTime = installTime;
	}

	@XmlTransient
	public TIMESTAMP getLastOnLine() {
		return lastOnLine;
	}

	public void setLastOnLine(TIMESTAMP lastOnLine) {
		this.lastOnLine = lastOnLine;
	}
	
	@XmlTransient
	public TIMESTAMP getLastOffLine() {
		return lastOffLine;
	}

	public void setLastOffLine(TIMESTAMP lastOffLine) {
		this.lastOffLine = lastOffLine;
	}

	@XmlTransient
	public INT getFailReason() {
		return failReason;
	}

	public void setFailReason(INT failReason) {
		this.failReason = failReason;
	}

	@XmlTransient
	public TIMESTAMP getBillingTime() {
		return billingTime;
	}

	public void setBillingTime(TIMESTAMP billingTime) {
		this.billingTime = billingTime;
	}

	@XmlTransient
	public BYTE getRelayStatus() {
		return relayStatus;
	}

	public void setRelayStatus(BYTE relayStatus) {
		this.relayStatus = relayStatus;
	}
	
	@XmlTransient
	public HEX getMeterModemId() {
		return meterModemId;
	}

	public void setMeterModemId(HEX meterModemId) {
		this.meterModemId = meterModemId;
	}

	public String toString()
    {
        StringBuffer sb = new StringBuffer();

        sb.append("CLASS["+this.getClass().getName()+"]\n");
        sb.append("meterId: " + meterId + "\n");
        sb.append("meterModel : " + meterModel  + "\n");
        sb.append("meterVendor : " + meterVendor  + "\n");
        sb.append("type : " + type  + "\n");
        sb.append("meterPhase : " + meterPhase + "\n");
        sb.append("meterModemId : " + meterModemId + "\n");
        sb.append("shortId : " + shortId + "\n");
        sb.append("status  : " + status  + "\n");
        sb.append("installTime  : " + installTime  + "\n");
        sb.append("lastOnLine  : " + lastOnLine  + "\n");
        sb.append("lastOffLine  : " + lastOffLine  + "\n");
        sb.append("failReason   : " + failReason   + "\n");
        sb.append("billingTime   : " + billingTime   + "\n");
        sb.append("relayStatus   : " + relayStatus   + "\n");

        return sb.toString();
    }
}
