package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * meterTimeSyncLogEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class meterTimeSyncLogEntry extends Entry {

	public TIMEDATE meterTimeSyncLogDate = 
			new TIMEDATE(4);

	public OCTET meterTimeSyncLogFileName = 
			new OCTET(32);

	public UINT meterTimeSyncLogFileSize = 
			new UINT();

	@XmlTransient
	public TIMEDATE getMeterTimeSyncLogDate()
	{
		 return this.meterTimeSyncLogDate;
	}

	public void setMeterTimeSyncLogDate(TIMEDATE meterTimeSyncLogDate)
	{
		 this.meterTimeSyncLogDate=meterTimeSyncLogDate;
	}

	@XmlTransient
	public OCTET getMeterTimeSyncLogFileName()
	{
		 return this.meterTimeSyncLogFileName;
	}

	public void setMeterTimeSyncLogFileName(OCTET meterTimeSyncLogFileName)
	{
		 this.meterTimeSyncLogFileName=meterTimeSyncLogFileName;
	}

	@XmlTransient
	public UINT getMeterTimeSyncLogFileSize()
	{
		 return this.meterTimeSyncLogFileSize;
	}

	public void setMeterTimeSyncLogFileSize(UINT meterTimeSyncLogFileSize)
	{
		 this.meterTimeSyncLogFileSize=meterTimeSyncLogFileSize;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("meterTimeSyncLogDate: " + meterTimeSyncLogDate + "\n");
		sb.append("meterTimeSyncLogFileName: " + meterTimeSyncLogFileName + "\n");
		sb.append("meterTimeSyncLogFileSize: " + meterTimeSyncLogFileSize + "\n");


        return sb.toString();
    }
}
