package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * meterDataEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class meterLPEntry extends Entry {

    public OCTET mlpId = 
        new OCTET(8);

    public OCTET mlpMid = 
            new OCTET(20);
    
    public BYTE mlpType = 
            new BYTE();
    
    public BYTE mlpServiceType = 
            new BYTE();
    
    public BYTE mlpVendor = 
        new BYTE();
    
    public WORD mlpDataCount = new WORD();
    
    public OCTET mlpData = 
            new OCTET();
    
    @XmlTransient
    public OCTET getMlpId()
    {
        return mlpId;
    }

    public void setMlpId(OCTET mlpId)
    {
        this.mlpId = mlpId;
    }

    @XmlTransient
    public OCTET getMlpMid()
    {
        return mlpMid;
    }

    public void setMlpMid(OCTET mlpMid)
    {
        this.mlpMid = mlpMid;
    }

    @XmlTransient
    public BYTE getMlpType()
    {
        return mlpType;
    }

    public void setMlpType(BYTE mlpType)
    {
        this.mlpType = mlpType;
    }

    @XmlTransient
    public BYTE getMlpVendor()
    {
        return mlpVendor;
    }

    public void setMlpVendor(BYTE mlpVendor)
    {
        this.mlpVendor = mlpVendor;
    }

    @XmlTransient
    public BYTE getMlpServiceType()
    {
        return mlpServiceType;
    }

    public void setMlpServiceType(BYTE mlpServiceType)
    {
        this.mlpServiceType = mlpServiceType;
    }

    @XmlTransient
    public WORD getMlpDataCount()
    {
        return mlpDataCount;
    }

    public void setMlpDataCount(WORD mlpDataCount)
    {
        this.mlpDataCount = mlpDataCount;
    }

    @XmlTransient
    public OCTET getMlpData()
    {
        return mlpData;
    }

    public void setMlpData(OCTET mlpData)
    {
        this.mlpData = mlpData;
    }


    public String toString()
    {
        StringBuffer sb = new StringBuffer();
    
        sb.append("CLASS["+this.getClass().getName()+"]\n");
        sb.append("mlpId: " + mlpId + "\n");
        sb.append("mlpMid: " + mlpMid + "\n");
        sb.append("mlpType: " + mlpType + "\n");
        sb.append("mlpVendor: " + mlpVendor + "\n");
        sb.append("mlpServiceType: " + mlpServiceType + "\n");
        sb.append("mlpDataCount: " + mlpDataCount + "\n");
        sb.append("mlpData: " + mlpData.toHexString() + "\n");
    
        return sb.toString();
    }
}
