package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * oidEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class oidEntry extends Entry {

	public BYTE oidDot1 = 
			new BYTE();

	public BYTE oidDot2 = 
			new BYTE();

	public BYTE oidDot3 = 
			new BYTE();

	@XmlTransient
	public BYTE getOidDot1()
	{
		 return this.oidDot1;
	}

	public void setOidDot1(BYTE oidDot1)
	{
		 this.oidDot1=oidDot1;
	}

	@XmlTransient
	public BYTE getOidDot2()
	{
		 return this.oidDot2;
	}

	public void setOidDot2(BYTE oidDot2)
	{
		 this.oidDot2=oidDot2;
	}

	@XmlTransient
	public BYTE getOidDot3()
	{
		 return this.oidDot3;
	}

	public void setOidDot3(BYTE oidDot3)
	{
		 this.oidDot3=oidDot3;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("oidDot1: " + oidDot1 + "\n");
		sb.append("oidDot2: " + oidDot2 + "\n");
		sb.append("oidDot3: " + oidDot3 + "\n");


        return sb.toString();
    }
}
