package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * pageEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class pageEntry extends Entry {

	public BYTE pageNumber = 
			new BYTE();

	public BYTE pageLength = 
			new BYTE();

	public OCTET pageData = 
			new OCTET();

	@XmlTransient
	public BYTE getPageNumber()
	{
		 return this.pageNumber;
	}

	public void setPageNumber(BYTE pageNumber)
	{
		 this.pageNumber=pageNumber;
	}

	@XmlTransient
	public BYTE getPageLength()
	{
		 return this.pageLength;
	}

	public void setPageLength(BYTE pageLength)
	{
		 this.pageLength=pageLength;
	}

	@XmlTransient
	public OCTET getPageData()
	{
		 return this.pageData;
	}

	public void setPageData(OCTET pageData)
	{
		 this.pageData=pageData;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("pageNumber: " + pageNumber + "\n");
		sb.append("pageLength: " + pageLength + "\n");
		sb.append("pageData: " + pageData + "\n");


        return sb.toString();
    }
}
