package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * pppEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class pppEntry extends Entry {

	public OCTET pppProvider = 
			new OCTET(16);

	public OCTET pppUser = 
			new OCTET(16);

	public OCTET pppPassword = 
			new OCTET(16);

	@XmlTransient
	public OCTET getPppProvider()
	{
		 return this.pppProvider;
	}

	public void setPppProvider(OCTET pppProvider)
	{
		 this.pppProvider=pppProvider;
	}

	@XmlTransient
	public OCTET getPppUser()
	{
		 return this.pppUser;
	}

	public void setPppUser(OCTET pppUser)
	{
		 this.pppUser=pppUser;
	}

	@XmlTransient
	public OCTET getPppPassword()
	{
		 return this.pppPassword;
	}

	public void setPppPassword(OCTET pppPassword)
	{
		 this.pppPassword=pppPassword;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("pppProvider: " + pppProvider + "\n");
		sb.append("pppUser: " + pppUser + "\n");
		sb.append("pppPassword: " + pppPassword + "\n");


        return sb.toString();
    }
}
