package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * procEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 * <pre>
 * &lt;complexType name="procEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{http://server.ws.command.fep.aimir.com/}entry">
 *       &lt;sequence>
 *         &lt;element name="procID" type="{http://server.ws.command.fep.aimir.com/}uint" minOccurs="0"/>
 *         &lt;element name="procTTY" type="{http://server.ws.command.fep.aimir.com/}octet" minOccurs="0"/>
 *         &lt;element name="procSize" type="{http://server.ws.command.fep.aimir.com/}uint" minOccurs="0"/>
 *         &lt;element name="procState" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="procCmd" type="{http://server.ws.command.fep.aimir.com/}octet" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "procEntry", propOrder = {
    "procID",
    "procTTY",
    "procSize",
    "procState",
    "procCmd"
})
public class procEntry extends Entry {

	public UINT procID = 
			new UINT();

	public OCTET procTTY = 
			new OCTET(8);

	public UINT procSize = 
			new UINT();

	public BYTE procState = 
			new BYTE();

	public OCTET procCmd = 
			new OCTET(50);

	@XmlTransient
	public UINT getProcID()
	{
		 return this.procID;
	}

	public void setProcID(UINT procID)
	{
		 this.procID=procID;
	}

	@XmlTransient
	public OCTET getProcTTY()
	{
		 return this.procTTY;
	}

	public void setProcTTY(OCTET procTTY)
	{
		 this.procTTY=procTTY;
	}

	@XmlTransient
	public UINT getProcSize()
	{
		 return this.procSize;
	}

	public void setProcSize(UINT procSize)
	{
		 this.procSize=procSize;
	}

	@XmlTransient
	public BYTE getProcState()
	{
		 return this.procState;
	}

	public void setProcState(BYTE procState)
	{
		 this.procState=procState;
	}

	@XmlTransient
	public OCTET getProcCmd()
	{
		 return this.procCmd;
	}

	public void setProcCmd(OCTET procCmd)
	{
		 this.procCmd=procCmd;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("procID: " + procID + "\n");
		sb.append("procTTY: " + procTTY + "\n");
		sb.append("procSize: " + procSize + "\n");
		sb.append("procState: " + procState + "\n");
		sb.append("procCmd: " + procCmd + "\n");


        return sb.toString();
    }
}
