package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * sensorConnectEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class sensorConnectEntry extends Entry {

	public HEX sensorID = 
			new HEX(8);

	public BYTE sensorType = 
			new BYTE();

	public TIMESTAMP sensorLastConnect = 
			new TIMESTAMP(7);

	public TIMESTAMP sensorLastDisconnect = 
			new TIMESTAMP(7);

	public TIMESTAMP sensorInstallDate = 
			new TIMESTAMP(7);

	public BYTE sensorPageCount = 
			new BYTE();

	public BYTE sensorState = 
			new BYTE();

	public BYTE sensorFlag = 
			new BYTE();

	public BYTE sensorVendor = 
			new BYTE();

	public OCTET sensorSerialNumber = 
			new OCTET(20);

	public BYTE sensorServiceType = 
			new BYTE();

	@XmlTransient
	public HEX getSensorID()
	{
		 return this.sensorID;
	}

	public void setSensorID(HEX sensorID)
	{
		 this.sensorID=sensorID;
	}

	@XmlTransient
	public BYTE getSensorType()
	{
		 return this.sensorType;
	}

	public void setSensorType(BYTE sensorType)
	{
		 this.sensorType=sensorType;
	}

	@XmlTransient
	public TIMESTAMP getSensorLastConnect()
	{
		 return this.sensorLastConnect;
	}

	public void setSensorLastConnect(TIMESTAMP sensorLastConnect)
	{
		 this.sensorLastConnect=sensorLastConnect;
	}

	@XmlTransient
	public TIMESTAMP getSensorLastDisconnect()
	{
		 return this.sensorLastDisconnect;
	}

	public void setSensorLastDisconnect(TIMESTAMP sensorLastDisconnect)
	{
		 this.sensorLastDisconnect=sensorLastDisconnect;
	}

	@XmlTransient
	public TIMESTAMP getSensorInstallDate()
	{
		 return this.sensorInstallDate;
	}

	public void setSensorInstallDate(TIMESTAMP sensorInstallDate)
	{
		 this.sensorInstallDate=sensorInstallDate;
	}

	@XmlTransient
	public BYTE getSensorPageCount()
	{
		 return this.sensorPageCount;
	}

	public void setSensorPageCount(BYTE sensorPageCount)
	{
		 this.sensorPageCount=sensorPageCount;
	}

	@XmlTransient
	public BYTE getSensorState()
	{
		 return this.sensorState;
	}

	public void setSensorState(BYTE sensorState)
	{
		 this.sensorState=sensorState;
	}

	@XmlTransient
	public BYTE getSensorFlag()
	{
		 return this.sensorFlag;
	}

	public void setSensorFlag(BYTE sensorFlag)
	{
		 this.sensorFlag=sensorFlag;
	}

	@XmlTransient
	public BYTE getSensorVendor()
	{
		 return this.sensorVendor;
	}

	public void setSensorVendor(BYTE sensorVendor)
	{
		 this.sensorVendor=sensorVendor;
	}

	@XmlTransient
	public OCTET getSensorSerialNumber()
	{
		 return this.sensorSerialNumber;
	}

	public void setSensorSerialNumber(OCTET sensorSerialNumber)
	{
		 this.sensorSerialNumber=sensorSerialNumber;
	}

	@XmlTransient
	public BYTE getSensorServiceType()
	{
		 return this.sensorServiceType;
	}

	public void setSensorServiceType(BYTE sensorServiceType)
	{
		 this.sensorServiceType=sensorServiceType;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("sensorID: " + sensorID + "\n");
		sb.append("sensorType: " + sensorType + "\n");
		sb.append("sensorLastConnect: " + sensorLastConnect + "\n");
		sb.append("sensorLastDisconnect: " + sensorLastDisconnect + "\n");
		sb.append("sensorInstallDate: " + sensorInstallDate + "\n");
		sb.append("sensorPageCount: " + sensorPageCount + "\n");
		sb.append("sensorState: " + sensorState + "\n");
		sb.append("sensorFlag: " + sensorFlag + "\n");
		sb.append("sensorVendor: " + sensorVendor + "\n");
		sb.append("sensorSerialNumber: " + sensorSerialNumber + "\n");
		sb.append("sensorServiceType: " + sensorServiceType + "\n");


        return sb.toString();
    }
}
