package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.BYTE;
import com.aimir.fep.protocol.fmp.datatype.WORD;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * sensorInfoEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class sensorBatteryEntry extends Entry {
    public WORD battVolt = new WORD(2);
    public WORD battCurrent = new WORD(2);
    public BYTE battOffset = new BYTE(1);

    @XmlTransient
    public WORD getBattVolt()
    {
        return battVolt;
    }

    public void setBattVolt(WORD battVolt)
    {
        this.battVolt = battVolt;
    }

    @XmlTransient
    public WORD getBattCurrent()
    {
        return battCurrent;
    }

    public void setBattCurrent(WORD battCurrent)
    {
        this.battCurrent = battCurrent;
    }

    @XmlTransient
    public BYTE getBattOffset()
    {
        return battOffset;
    }

    public void setBattOffset(BYTE battOffset)
    {
        this.battOffset = battOffset;
    }

    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("battVolt: " + battVolt + "\n");
		sb.append("battCurrent: " + battCurrent + "\n");
		sb.append("battOffset: " + battOffset + "\n");

        return sb.toString();
    }
}
