package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * sensorInfoNewEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2007-11-13 15:59:15 +0900 $,
 * <pre>
 * &lt;complexType name="sensorInfoNewEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{http://server.ws.command.fep.aimir.com/}entry">
 *       &lt;sequence>
 *         &lt;element name="sensorID" type="{http://server.ws.command.fep.aimir.com/}hex" minOccurs="0"/>
 *         &lt;element name="sensorSerial" type="{http://server.ws.command.fep.aimir.com/}octet" minOccurs="0"/>
 *         &lt;element name="sensorLastConnect" type="{http://server.ws.command.fep.aimir.com/}timestamp" minOccurs="0"/>
 *         &lt;element name="sensorInstallDate" type="{http://server.ws.command.fep.aimir.com/}timestamp" minOccurs="0"/>
 *         &lt;element name="sensorAttr" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="sensorState" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="sensorModel" type="{http://server.ws.command.fep.aimir.com/}octet" minOccurs="0"/>
 *         &lt;element name="sensorHwVersion" type="{http://server.ws.command.fep.aimir.com/}word" minOccurs="0"/>
 *         &lt;element name="sensorFwVersion" type="{http://server.ws.command.fep.aimir.com/}word" minOccurs="0"/>
 *         &lt;element name="sensorOTAState" type="{http://server.ws.command.fep.aimir.com/}byte" minOccurs="0"/>
 *         &lt;element name="sensorLastOTATime" type="{http://server.ws.command.fep.aimir.com/}timestamp" minOccurs="0"/>
 *         &lt;element name="sensorFwBuild" type="{http://server.ws.command.fep.aimir.com/}word" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sensorInfoNewEntry", propOrder = {
    "sensorID",
    "sensorSerial",
    "sensorLastConnect",
    "sensorInstallDate",
    "sensorAttr",
    "sensorState",
    "sensorModel",
    "sensorHwVersion",
    "sensorFwVersion",
    "sensorOTAState",
    "sensorLastOTATime",
    "sensorFwBuild"
})
public class sensorInfoNewEntry extends Entry {

    public HEX  sensorID =
            new HEX(8);

	public OCTET sensorSerial = 
			new OCTET(20);

	public TIMESTAMP sensorLastConnect = 
			new TIMESTAMP(7);

	public TIMESTAMP sensorInstallDate = 
			new TIMESTAMP(7);
	
	public BYTE sensorAttr = new BYTE();
	
	public BYTE sensorState = new BYTE();
    
    public OCTET sensorModel = 
            new OCTET(18);
    
    public WORD sensorHwVersion = 
            new WORD();
    
    public WORD sensorFwVersion = 
            new WORD();

    public BYTE sensorOTAState = new BYTE();
    
    public TIMESTAMP sensorLastOTATime = new TIMESTAMP(7);
    
    public WORD sensorFwBuild = new WORD();
    
    @XmlTransient
	public HEX getSensorID()
	{
		 return this.sensorID;
	}

	public void setSensorID(HEX sensorID)
	{
		 this.sensorID=sensorID;
	}

	@XmlTransient
	public OCTET getSensorSerial()
	{
		 return this.sensorSerial;
	}

	public void setSensorSerial(OCTET sensorSerial)
	{
		 this.sensorSerial=sensorSerial;
	}

	@XmlTransient
	public TIMESTAMP getSensorLastConnect()
	{
		 return this.sensorLastConnect;
	}

	public void setSensorLastConnect(TIMESTAMP sensorLastConnect)
	{
		 this.sensorLastConnect=sensorLastConnect;
	}

	@XmlTransient
	public TIMESTAMP getSensorInstallDate()
	{
		 return this.sensorInstallDate;
	}

	public void setSensorInstallDate(TIMESTAMP sensorInstallDate)
	{
		 this.sensorInstallDate=sensorInstallDate;
	}

	@XmlTransient
    public BYTE getSensorAttr()
    {
        return sensorAttr;
    }

    public void setSensorAttr(BYTE sensorAttr)
    {
        this.sensorAttr = sensorAttr;
    }

    @XmlTransient
    public BYTE getSensorState()
    {
        return sensorState;
    }

    public void setSensorState(BYTE sensorState)
    {
        this.sensorState = sensorState;
    }
        
    @XmlTransient
    public OCTET getSensorModel(){
        return sensorModel;
    }

    @XmlTransient
    public WORD getSensorHwVersion()
    {
        return sensorHwVersion;
    }

    @XmlTransient
    public WORD getSensorFwVersion()
    {
        return sensorFwVersion;
    }
    
    public void setSensorModel(OCTET sensorModel){
        this.sensorModel = sensorModel;
    }

    public void setSensorHwVersion(WORD sensorHwVersion)
    {
        this.sensorHwVersion = sensorHwVersion;
    }

    public void setSensorFwVersion(WORD sensorFwVersion)
    {
        this.sensorFwVersion = sensorFwVersion;
    }

    @XmlTransient
    public BYTE getSensorOTAState()
    {
        return sensorOTAState;
    }

    public void setSensorOTAState(BYTE sensorOTAState)
    {
        this.sensorOTAState = sensorOTAState;
    }

    @XmlTransient
    public TIMESTAMP getSensorLastOTATime()
    {
        return sensorLastOTATime;
    }

    public void setSensorLastOTATime(TIMESTAMP sensorLastOTATime)
    {
        this.sensorLastOTATime = sensorLastOTATime;
    }

    @XmlTransient
    public WORD getSensorFwBuild()
    {
        return sensorFwBuild;
    }

    public void setSensorFwBuild(WORD sensorFwBuild)
    {
        this.sensorFwBuild = sensorFwBuild;
    }

    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("sensorID: " + sensorID + "\n");
		sb.append("sensorSerial: " + sensorSerial + "\n");
		sb.append("sensorLastConnect: " + sensorLastConnect + "\n");
		sb.append("sensorInstallDate: " + sensorInstallDate + "\n");
		sb.append("sensorAttr: " + sensorAttr + "\n");
		sb.append("sensorState: " + sensorState + "\n");
        sb.append("sensorModel: " + sensorModel + "\n");
        sb.append("sensorHwVersion: " + sensorHwVersion + "\n");
        sb.append("sensorFwVersion: " + sensorFwVersion + "\n");
        sb.append("sensorOTAState: " + sensorOTAState + "\n");
        sb.append("sensorLastOTATime: " + sensorLastOTATime + "\n");
        sb.append("sensorFwBuild: " + sensorFwBuild + "\n");
        return sb.toString();
    }
}
