package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * varEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "varEntry", propOrder = {
    "varEnableMask",
    "varEnableRecovery",
    "varEnableCmdHistLog",
    "varEnableCommLog",
    "varEanbleAutoRegister",
    "varEnableAutoReset",
    "varEnableAutoTimeSync",
    "varEnableAutoSinkReset",
    "varEnableSubNetwork",
    "varEnableMobileStaticLog",
    "varEnableAutoUpload",
    "varEnableSecurity",
    "varEnableMonitoring",
    "varEnableKeepalive",
    "varEnableGpsTimesync",
    "varEnableTimeBroadcast",
    "varEnableStatusMonitoring",
    "varEnableMemoryCheck",
    "varEnableFlashCheck",
    "varEnableMeterTimesync",
    "varEnableMeterCheck",
    "varEnableHeater",
    "varEnableReadMeterEvent"
})
public class varEntry extends Entry {

	public UINT varEnableMask = 
			new UINT();

	public BOOL varEnableRecovery = 
			new BOOL();

	public BOOL varEnableCmdHistLog = 
			new BOOL();

	public BOOL varEnableCommLog = 
			new BOOL();

	public BOOL varEanbleAutoRegister = 
			new BOOL();

	public BOOL varEnableAutoReset = 
			new BOOL();

	public BOOL varEnableAutoTimeSync = 
			new BOOL();

	public BOOL varEnableAutoSinkReset = 
			new BOOL();

	public BOOL varEnableSubNetwork = 
			new BOOL();

	public BOOL varEnableMobileStaticLog = 
			new BOOL();

	public BOOL varEnableAutoUpload = 
			new BOOL();

	public BOOL varEnableSecurity = 
			new BOOL();

	public BOOL varEnableMonitoring = new BOOL();
	
	public BOOL varEnableKeepalive = new BOOL();
	
	public BOOL varEnableGpsTimesync = new BOOL();
	
	public BOOL varEnableTimeBroadcast = new BOOL();
	
	public BOOL varEnableStatusMonitoring = new BOOL();
	
	public BOOL varEnableMemoryCheck = new BOOL();
	
	public BOOL varEnableFlashCheck = new BOOL();
	
	public BOOL varEnableMeterTimesync = new BOOL();
	
	public BOOL varEnableMeterCheck = new BOOL();
	
	public BOOL varEnableHeater = new BOOL();
	
	public BOOL varEnableReadMeterEvent = new BOOL();

	@XmlTransient
	public UINT getVarEnableMask()
	{
		 return this.varEnableMask;
	}

	public void setVarEnableMask(UINT varEnableMask)
	{
		 this.varEnableMask=varEnableMask;
	}

	@XmlTransient
	public BOOL getVarEnableRecovery()
	{
		 return this.varEnableRecovery;
	}

	public void setVarEnableRecovery(BOOL varEnableRecovery)
	{
		 this.varEnableRecovery=varEnableRecovery;
	}

	@XmlTransient
	public BOOL getVarEnableCmdHistLog()
	{
		 return this.varEnableCmdHistLog;
	}

	public void setVarEnableCmdHistLog(BOOL varEnableCmdHistLog)
	{
		 this.varEnableCmdHistLog=varEnableCmdHistLog;
	}

	@XmlTransient
	public BOOL getVarEnableCommLog()
	{
		 return this.varEnableCommLog;
	}

	public void setVarEnableCommLog(BOOL varEnableCommLog)
	{
		 this.varEnableCommLog=varEnableCommLog;
	}

	@XmlTransient
	public BOOL getVarEanbleAutoRegister()
	{
		 return this.varEanbleAutoRegister;
	}

	public void setVarEanbleAutoRegister(BOOL varEanbleAutoRegister)
	{
		 this.varEanbleAutoRegister=varEanbleAutoRegister;
	}

	@XmlTransient
	public BOOL getVarEnableAutoReset()
	{
		 return this.varEnableAutoReset;
	}

	public void setVarEnableAutoReset(BOOL varEnableAutoReset)
	{
		 this.varEnableAutoReset=varEnableAutoReset;
	}

	@XmlTransient
	public BOOL getVarEnableAutoTimeSync()
	{
		 return this.varEnableAutoTimeSync;
	}

	public void setVarEnableAutoTimeSync(BOOL varEnableAutoTimeSync)
	{
		 this.varEnableAutoTimeSync=varEnableAutoTimeSync;
	}

	@XmlTransient
	public BOOL getVarEnableAutoSinkReset()
	{
		 return this.varEnableAutoSinkReset;
	}

	public void setVarEnableAutoSinkReset(BOOL varEnableAutoSinkReset)
	{
		 this.varEnableAutoSinkReset=varEnableAutoSinkReset;
	}

	@XmlTransient
	public BOOL getVarEnableSubNetwork()
	{
		 return this.varEnableSubNetwork;
	}

	public void setVarEnableSubNetwork(BOOL varEnableSubNetwork)
	{
		 this.varEnableSubNetwork=varEnableSubNetwork;
	}

	@XmlTransient
	public BOOL getVarEnableMobileStaticLog()
	{
		 return this.varEnableMobileStaticLog;
	}

	public void setVarEnableMobileStaticLog(BOOL varEnableMobileStaticLog)
	{
		 this.varEnableMobileStaticLog=varEnableMobileStaticLog;
	}

	@XmlTransient
	public BOOL getVarEnableAutoUpload()
	{
		 return this.varEnableAutoUpload;
	}

	public void setVarEnableAutoUpload(BOOL varEnableAutoUpload)
	{
		 this.varEnableAutoUpload=varEnableAutoUpload;
	}

	@XmlTransient
	public BOOL getVarEnableSecurity()
	{
		 return this.varEnableSecurity;
	}

	public void setVarEnableSecurity(BOOL varEnableSecurity)
	{
		 this.varEnableSecurity=varEnableSecurity;
	}

	@XmlTransient
    public BOOL getVarEnableMonitoring()
    {
        return varEnableMonitoring;
    }

    public void setVarEnableMonitoring(BOOL varEnableMonitoring)
    {
        this.varEnableMonitoring = varEnableMonitoring;
    }

    @XmlTransient
    public BOOL getVarEnableKeepalive()
    {
        return varEnableKeepalive;
    }

    public void setVarEnableKeepalive(BOOL varEnableKeepalive)
    {
        this.varEnableKeepalive = varEnableKeepalive;
    }

    @XmlTransient
    public BOOL getVarEnableGpsTimesync()
    {
        return varEnableGpsTimesync;
    }

    public void setVarEnableGpsTimesync(BOOL varEnableGpsTimesync)
    {
        this.varEnableGpsTimesync = varEnableGpsTimesync;
    }

    @XmlTransient
    public BOOL getVarEnableTimeBroadcast()
    {
        return varEnableTimeBroadcast;
    }

    public void setVarEnableTimeBroadcast(BOOL varEnableTimeBroadcast)
    {
        this.varEnableTimeBroadcast = varEnableTimeBroadcast;
    }

    @XmlTransient
    public BOOL getVarEnableStatusMonitoring()
    {
        return varEnableStatusMonitoring;
    }

    public void setVarEnableStatusMonitoring(BOOL varEnableStatusMonitoring)
    {
        this.varEnableStatusMonitoring = varEnableStatusMonitoring;
    }

    @XmlTransient
    public BOOL getVarEnableMemoryCheck()
    {
        return varEnableMemoryCheck;
    }

    public void setVarEnableMemoryCheck(BOOL varEnableMemoryCheck)
    {
        this.varEnableMemoryCheck = varEnableMemoryCheck;
    }

    @XmlTransient
    public BOOL getVarEnableFlashCheck()
    {
        return varEnableFlashCheck;
    }

    public void setVarEnableFlashCheck(BOOL varEnableFlashCheck)
    {
        this.varEnableFlashCheck = varEnableFlashCheck;
    }

    @XmlTransient
    public BOOL getVarEnableMeterTimesync()
    {
        return varEnableMeterTimesync;
    }

    public void setVarEnableMeterTimesync(BOOL varEnableMeterTimesync)
    {
        this.varEnableMeterTimesync = varEnableMeterTimesync;
    }

    @XmlTransient
    public BOOL getVarEnableMeterCheck()
    {
        return varEnableMeterCheck;
    }

    public void setVarEnableMeterCheck(BOOL varEnableMeterCheck)
    {
        this.varEnableMeterCheck = varEnableMeterCheck;
    }

    @XmlTransient
    public BOOL getVarEnableHeater()
    {
        return varEnableHeater;
    }

    public void setVarEnableHeater(BOOL varEnableHeater)
    {
        this.varEnableHeater = varEnableHeater;
    }

    @XmlTransient
    public BOOL getVarEnableReadMeterEvent()
    {
        return varEnableReadMeterEvent;
    }

    public void setVarEnableReadMeterEvent(BOOL varEnableReadMeterEvent)
    {
        this.varEnableReadMeterEvent = varEnableReadMeterEvent;
    }

    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("varEnableMask: " + varEnableMask + "\n");
		sb.append("varEnableRecovery: " + varEnableRecovery + "\n");
		sb.append("varEnableCmdHistLog: " + varEnableCmdHistLog + "\n");
		sb.append("varEnableCommLog: " + varEnableCommLog + "\n");
		sb.append("varEanbleAutoRegister: " + varEanbleAutoRegister + "\n");
		sb.append("varEnableAutoReset: " + varEnableAutoReset + "\n");
		sb.append("varEnableAutoTimeSync: " + varEnableAutoTimeSync + "\n");
		sb.append("varEnableAutoSinkReset: " + varEnableAutoSinkReset + "\n");
		sb.append("varEnableSubNetwork: " + varEnableSubNetwork + "\n");
		sb.append("varEnableMobileStaticLog: " + varEnableMobileStaticLog + "\n");
		sb.append("varEnableAutoUpload: " + varEnableAutoUpload + "\n");
		sb.append("varEnableSecurity: " + varEnableSecurity + "\n");
		sb.append("varEnableMonitoring: " + varEnableMonitoring + "\n");
		sb.append("varEnableKeepalive: " + varEnableKeepalive + "\n");
		sb.append("varEnableGpsTimesync: " + varEnableGpsTimesync + "\n");
		sb.append("varEnableTimeBroadcast: " + varEnableTimeBroadcast + "\n");
		sb.append("varEnableStatusMonitoring: " + varEnableStatusMonitoring + "\n");
		sb.append("varEnableMemoryCheck: " + varEnableMemoryCheck + "\n");
		sb.append("varEnableFlashCheck: " + varEnableFlashCheck + "\n");
		sb.append("varEnableMeterTimesync: " + varEnableMeterTimesync + "\n");
		sb.append("varEnableMeterCheck: " + varEnableMeterCheck + "\n");
		sb.append("varEnableHeater: " + varEnableHeater + "\n");
		sb.append("varEnableReadMeterEvent: " + varEnableReadMeterEvent + "\n");
		
        return sb.toString();
    }
}
