package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * varSubValueEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "varSubValueEntry", propOrder = {
    "varSubValueMask",
    "varSubChannel",
    "varSubPanID"
})
public class varSubValueEntry extends Entry {

	public UINT varSubValueMask = 
			new UINT();

	public BYTE varSubChannel = 
			new BYTE();

	public WORD varSubPanID = 
			new WORD();

	@XmlTransient
	public UINT getVarSubValueMask()
	{
		 return this.varSubValueMask;
	}

	public void setVarSubValueMask(UINT varSubValueMask)
	{
		 this.varSubValueMask=varSubValueMask;
	}

	@XmlTransient
	public BYTE getVarSubChannel()
	{
		 return this.varSubChannel;
	}

	public void setVarSubChannel(BYTE varSubChannel)
	{
		 this.varSubChannel=varSubChannel;
	}

	@XmlTransient
	public WORD getVarSubPanID()
	{
		 return this.varSubPanID;
	}

	public void setVarSubPanID(WORD varSubPanID)
	{
		 this.varSubPanID=varSubPanID;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("varSubValueMask: " + varSubValueMask + "\n");
		sb.append("varSubChannel: " + varSubChannel + "\n");
		sb.append("varSubPanID: " + varSubPanID + "\n");


        return sb.toString();
    }
}
