package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * verEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class verEntry extends Entry {

	public OCTET verPrefix = 
			new OCTET(3);

	public BYTE verFixed1 = 
			new BYTE();

	public OCTET verHwVersion = 
			new OCTET(2);

	public BYTE verFixed2 = 
			new BYTE();

	public OCTET verSwVersion = 
			new OCTET(4);

	public BYTE verFixed3 = 
			new BYTE();

	public OCTET verService = 
			new OCTET(4);

	@XmlTransient
	public OCTET getVerPrefix()
	{
		 return this.verPrefix;
	}

	public void setVerPrefix(OCTET verPrefix)
	{
		 this.verPrefix=verPrefix;
	}

	@XmlTransient
	public BYTE getVerFixed1()
	{
		 return this.verFixed1;
	}

	public void setVerFixed1(BYTE verFixed1)
	{
		 this.verFixed1=verFixed1;
	}

	@XmlTransient
	public OCTET getVerHwVersion()
	{
		 return this.verHwVersion;
	}

	public void setVerHwVersion(OCTET verHwVersion)
	{
		 this.verHwVersion=verHwVersion;
	}

	@XmlTransient
	public BYTE getVerFixed2()
	{
		 return this.verFixed2;
	}

	public void setVerFixed2(BYTE verFixed2)
	{
		 this.verFixed2=verFixed2;
	}

	@XmlTransient
	public OCTET getVerSwVersion()
	{
		 return this.verSwVersion;
	}

	public void setVerSwVersion(OCTET verSwVersion)
	{
		 this.verSwVersion=verSwVersion;
	}

	@XmlTransient
	public BYTE getVerFixed3()
	{
		 return this.verFixed3;
	}

	public void setVerFixed3(BYTE verFixed3)
	{
		 this.verFixed3=verFixed3;
	}

	@XmlTransient
	public OCTET getVerService()
	{
		 return this.verService;
	}

	public void setVerService(OCTET verService)
	{
		 this.verService=verService;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("verPrefix: " + verPrefix + "\n");
		sb.append("verFixed1: " + verFixed1 + "\n");
		sb.append("verHwVersion: " + verHwVersion + "\n");
		sb.append("verFixed2: " + verFixed2 + "\n");
		sb.append("verSwVersion: " + verSwVersion + "\n");
		sb.append("verFixed3: " + verFixed3 + "\n");
		sb.append("verService: " + verService + "\n");


        return sb.toString();
    }
}
