package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * commLogStruct
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "commLogStruct", propOrder = {
        "commLogLength",
        "commLogMin",
        "commLogSec",
        "commLogData"
})
public class commLogStruct extends Entry {

	public BYTE commLogLength = 
			new BYTE();

	public BYTE commLogMin = 
			new BYTE();

	public BYTE commLogSec = 
			new BYTE();

	public OCTET commLogData = 
			new OCTET();

	@XmlTransient
	public BYTE getCommLogLength()
	{
		 return this.commLogLength;
	}

	public void setCommLogLength(BYTE commLogLength)
	{
		 this.commLogLength=commLogLength;
	}

	@XmlTransient
	public BYTE getCommLogMin()
	{
		 return this.commLogMin;
	}

	public void setCommLogMin(BYTE commLogMin)
	{
		 this.commLogMin=commLogMin;
	}

	@XmlTransient
	public BYTE getCommLogSec()
	{
		 return this.commLogSec;
	}

	public void setCommLogSec(BYTE commLogSec)
	{
		 this.commLogSec=commLogSec;
	}

	@XmlTransient
	public OCTET getCommLogData()
	{
		 return this.commLogData;
	}

	public void setCommLogData(OCTET commLogData)
	{
		 this.commLogData=commLogData;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("commLogLength: " + commLogLength + "\n");
		sb.append("commLogMin: " + commLogMin + "\n");
		sb.append("commLogSec: " + commLogSec + "\n");
		sb.append("commLogData: " + commLogData + "\n");


        return sb.toString();
    }
}
