package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * mobileLogEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class mobileLogEntry extends Entry {

	public TIMEDATE mobileLogDate = 
			new TIMEDATE(4);

	public OCTET mobileLogFileName = 
			new OCTET(32);

	public UINT mobileLogFileSize = 
			new UINT();

	@XmlTransient
	public TIMEDATE getMobileLogDate()
	{
		 return this.mobileLogDate;
	}

	public void setMobileLogDate(TIMEDATE mobileLogDate)
	{
		 this.mobileLogDate=mobileLogDate;
	}

	@XmlTransient
	public OCTET getMobileLogFileName()
	{
		 return this.mobileLogFileName;
	}

	public void setMobileLogFileName(OCTET mobileLogFileName)
	{
		 this.mobileLogFileName=mobileLogFileName;
	}

	@XmlTransient
	public UINT getMobileLogFileSize()
	{
		 return this.mobileLogFileSize;
	}

	public void setMobileLogFileSize(UINT mobileLogFileSize)
	{
		 this.mobileLogFileSize=mobileLogFileSize;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("mobileLogDate: " + mobileLogDate + "\n");
		sb.append("mobileLogFileName: " + mobileLogFileName + "\n");
		sb.append("mobileLogFileSize: " + mobileLogFileSize + "\n");


        return sb.toString();
    }
}
