package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * ipEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class ipEntry extends Entry {

	public BYTE ipDot1 = 
			new BYTE();

	public BYTE ipDot2 = 
			new BYTE();

	public BYTE ipDot3 = 
			new BYTE();

	public BYTE ipDot4 = 
			new BYTE();

	@XmlTransient
	public BYTE getIpDot1()
	{
		 return this.ipDot1;
	}

	public void setIpDot1(BYTE ipDot1)
	{
		 this.ipDot1=ipDot1;
	}

	@XmlTransient
	public BYTE getIpDot2()
	{
		 return this.ipDot2;
	}

	public void setIpDot2(BYTE ipDot2)
	{
		 this.ipDot2=ipDot2;
	}

	@XmlTransient
	public BYTE getIpDot3()
	{
		 return this.ipDot3;
	}

	public void setIpDot3(BYTE ipDot3)
	{
		 this.ipDot3=ipDot3;
	}

	@XmlTransient
	public BYTE getIpDot4()
	{
		 return this.ipDot4;
	}

	public void setIpDot4(BYTE ipDot4)
	{
		 this.ipDot4=ipDot4;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("ipDot1: " + ipDot1 + "\n");
		sb.append("ipDot2: " + ipDot2 + "\n");
		sb.append("ipDot3: " + ipDot3 + "\n");
		sb.append("ipDot4: " + ipDot4 + "\n");


        return sb.toString();
    }
}
