package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * mobileLogStruct
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class mobileLogStruct extends Entry {

	public UINT mobileLogRecv00 = 
			new UINT();

	public UINT mobileLogSend00 = 
			new UINT();

	public UINT mobileLogRecv01 = 
			new UINT();

	public UINT mobileLogSend01 = 
			new UINT();

	public UINT mobileLogRecv02 = 
			new UINT();

	public UINT mobileLogSend02 = 
			new UINT();

	public UINT mobileLogRecv03 = 
			new UINT();

	public UINT mobileLogSend03 = 
			new UINT();

	public UINT mobileLogRecv04 = 
			new UINT();

	public UINT mobileLogSend04 = 
			new UINT();

	public UINT mobileLogRecv05 = 
			new UINT();

	public UINT mobileLogSend05 = 
			new UINT();

	public UINT mobileLogRecv06 = 
			new UINT();

	public UINT mobileLogSend06 = 
			new UINT();

	public UINT mobileLogRecv07 = 
			new UINT();

	public UINT mobileLogSend07 = 
			new UINT();

	public UINT mobileLogRecv08 = 
			new UINT();

	public UINT mobileLogSend08 = 
			new UINT();

	public UINT mobileLogRecv09 = 
			new UINT();

	public UINT mobileLogSend09 = 
			new UINT();

	public UINT mobileLogRecv10 = 
			new UINT();

	public UINT mobileLogSend10 = 
			new UINT();

	public UINT mobileLogRecv11 = 
			new UINT();

	public UINT mobileLogSend11 = 
			new UINT();

	public UINT mobileLogRecv12 = 
			new UINT();

	public UINT mobileLogSend12 = 
			new UINT();

	public UINT mobileLogRecv13 = 
			new UINT();

	public UINT mobileLogSend13 = 
			new UINT();

	public UINT mobileLogRecv14 = 
			new UINT();

	public UINT mobileLogSend14 = 
			new UINT();

	public UINT mobileLogRecv15 = 
			new UINT();

	public UINT mobileLogSend15 = 
			new UINT();

	public UINT mobileLogRecv16 = 
			new UINT();

	public UINT mobileLogSend16 = 
			new UINT();

	public UINT mobileLogRecv17 = 
			new UINT();

	public UINT mobileLogSend17 = 
			new UINT();

	public UINT mobileLogRecv18 = 
			new UINT();

	public UINT mobileLogSend18 = 
			new UINT();

	public UINT mobileLogRecv19 = 
			new UINT();

	public UINT mobileLogSend19 = 
			new UINT();

	public UINT mobileLogRecv20 = 
			new UINT();

	public UINT mobileLogSend20 = 
			new UINT();

	public UINT mobileLogRecv21 = 
			new UINT();

	public UINT mobileLogSend21 = 
			new UINT();

	public UINT mobileLogRecv22 = 
			new UINT();

	public UINT mobileLogSend22 = 
			new UINT();

	public UINT mobileLogRecv23 = 
			new UINT();

	public UINT mobileLogSend23 = 
			new UINT();

	@XmlTransient
	public UINT getMobileLogRecv00()
	{
		 return this.mobileLogRecv00;
	}

	public void setMobileLogRecv00(UINT mobileLogRecv00)
	{
		 this.mobileLogRecv00=mobileLogRecv00;
	}

	@XmlTransient
	public UINT getMobileLogSend00()
	{
		 return this.mobileLogSend00;
	}

	public void setMobileLogSend00(UINT mobileLogSend00)
	{
		 this.mobileLogSend00=mobileLogSend00;
	}

	@XmlTransient
	public UINT getMobileLogRecv01()
	{
		 return this.mobileLogRecv01;
	}

	public void setMobileLogRecv01(UINT mobileLogRecv01)
	{
		 this.mobileLogRecv01=mobileLogRecv01;
	}

	@XmlTransient
	public UINT getMobileLogSend01()
	{
		 return this.mobileLogSend01;
	}

	public void setMobileLogSend01(UINT mobileLogSend01)
	{
		 this.mobileLogSend01=mobileLogSend01;
	}

	@XmlTransient
	public UINT getMobileLogRecv02()
	{
		 return this.mobileLogRecv02;
	}

	public void setMobileLogRecv02(UINT mobileLogRecv02)
	{
		 this.mobileLogRecv02=mobileLogRecv02;
	}

	@XmlTransient
	public UINT getMobileLogSend02()
	{
		 return this.mobileLogSend02;
	}

	public void setMobileLogSend02(UINT mobileLogSend02)
	{
		 this.mobileLogSend02=mobileLogSend02;
	}

	@XmlTransient
	public UINT getMobileLogRecv03()
	{
		 return this.mobileLogRecv03;
	}

	public void setMobileLogRecv03(UINT mobileLogRecv03)
	{
		 this.mobileLogRecv03=mobileLogRecv03;
	}

	@XmlTransient
	public UINT getMobileLogSend03()
	{
		 return this.mobileLogSend03;
	}

	public void setMobileLogSend03(UINT mobileLogSend03)
	{
		 this.mobileLogSend03=mobileLogSend03;
	}

	@XmlTransient
	public UINT getMobileLogRecv04()
	{
		 return this.mobileLogRecv04;
	}

	public void setMobileLogRecv04(UINT mobileLogRecv04)
	{
		 this.mobileLogRecv04=mobileLogRecv04;
	}

	@XmlTransient
	public UINT getMobileLogSend04()
	{
		 return this.mobileLogSend04;
	}

	public void setMobileLogSend04(UINT mobileLogSend04)
	{
		 this.mobileLogSend04=mobileLogSend04;
	}

	@XmlTransient
	public UINT getMobileLogRecv05()
	{
		 return this.mobileLogRecv05;
	}

	public void setMobileLogRecv05(UINT mobileLogRecv05)
	{
		 this.mobileLogRecv05=mobileLogRecv05;
	}

	@XmlTransient
	public UINT getMobileLogSend05()
	{
		 return this.mobileLogSend05;
	}

	public void setMobileLogSend05(UINT mobileLogSend05)
	{
		 this.mobileLogSend05=mobileLogSend05;
	}

	@XmlTransient
	public UINT getMobileLogRecv06()
	{
		 return this.mobileLogRecv06;
	}

	public void setMobileLogRecv06(UINT mobileLogRecv06)
	{
		 this.mobileLogRecv06=mobileLogRecv06;
	}

	@XmlTransient
	public UINT getMobileLogSend06()
	{
		 return this.mobileLogSend06;
	}

	public void setMobileLogSend06(UINT mobileLogSend06)
	{
		 this.mobileLogSend06=mobileLogSend06;
	}

	@XmlTransient
	public UINT getMobileLogRecv07()
	{
		 return this.mobileLogRecv07;
	}

	public void setMobileLogRecv07(UINT mobileLogRecv07)
	{
		 this.mobileLogRecv07=mobileLogRecv07;
	}

	@XmlTransient
	public UINT getMobileLogSend07()
	{
		 return this.mobileLogSend07;
	}

	public void setMobileLogSend07(UINT mobileLogSend07)
	{
		 this.mobileLogSend07=mobileLogSend07;
	}

	@XmlTransient
	public UINT getMobileLogRecv08()
	{
		 return this.mobileLogRecv08;
	}

	public void setMobileLogRecv08(UINT mobileLogRecv08)
	{
		 this.mobileLogRecv08=mobileLogRecv08;
	}

	@XmlTransient
	public UINT getMobileLogSend08()
	{
		 return this.mobileLogSend08;
	}

	public void setMobileLogSend08(UINT mobileLogSend08)
	{
		 this.mobileLogSend08=mobileLogSend08;
	}

	@XmlTransient
	public UINT getMobileLogRecv09()
	{
		 return this.mobileLogRecv09;
	}

	public void setMobileLogRecv09(UINT mobileLogRecv09)
	{
		 this.mobileLogRecv09=mobileLogRecv09;
	}

	@XmlTransient
	public UINT getMobileLogSend09()
	{
		 return this.mobileLogSend09;
	}

	public void setMobileLogSend09(UINT mobileLogSend09)
	{
		 this.mobileLogSend09=mobileLogSend09;
	}

	@XmlTransient
	public UINT getMobileLogRecv10()
	{
		 return this.mobileLogRecv10;
	}

	public void setMobileLogRecv10(UINT mobileLogRecv10)
	{
		 this.mobileLogRecv10=mobileLogRecv10;
	}

	@XmlTransient
	public UINT getMobileLogSend10()
	{
		 return this.mobileLogSend10;
	}

	public void setMobileLogSend10(UINT mobileLogSend10)
	{
		 this.mobileLogSend10=mobileLogSend10;
	}

	@XmlTransient
	public UINT getMobileLogRecv11()
	{
		 return this.mobileLogRecv11;
	}

	public void setMobileLogRecv11(UINT mobileLogRecv11)
	{
		 this.mobileLogRecv11=mobileLogRecv11;
	}

	@XmlTransient
	public UINT getMobileLogSend11()
	{
		 return this.mobileLogSend11;
	}

	public void setMobileLogSend11(UINT mobileLogSend11)
	{
		 this.mobileLogSend11=mobileLogSend11;
	}

	@XmlTransient
	public UINT getMobileLogRecv12()
	{
		 return this.mobileLogRecv12;
	}

	public void setMobileLogRecv12(UINT mobileLogRecv12)
	{
		 this.mobileLogRecv12=mobileLogRecv12;
	}

	@XmlTransient
	public UINT getMobileLogSend12()
	{
		 return this.mobileLogSend12;
	}

	public void setMobileLogSend12(UINT mobileLogSend12)
	{
		 this.mobileLogSend12=mobileLogSend12;
	}

	@XmlTransient
	public UINT getMobileLogRecv13()
	{
		 return this.mobileLogRecv13;
	}

	public void setMobileLogRecv13(UINT mobileLogRecv13)
	{
		 this.mobileLogRecv13=mobileLogRecv13;
	}

	@XmlTransient
	public UINT getMobileLogSend13()
	{
		 return this.mobileLogSend13;
	}

	public void setMobileLogSend13(UINT mobileLogSend13)
	{
		 this.mobileLogSend13=mobileLogSend13;
	}

	@XmlTransient
	public UINT getMobileLogRecv14()
	{
		 return this.mobileLogRecv14;
	}

	public void setMobileLogRecv14(UINT mobileLogRecv14)
	{
		 this.mobileLogRecv14=mobileLogRecv14;
	}

	@XmlTransient
	public UINT getMobileLogSend14()
	{
		 return this.mobileLogSend14;
	}

	public void setMobileLogSend14(UINT mobileLogSend14)
	{
		 this.mobileLogSend14=mobileLogSend14;
	}

	@XmlTransient
	public UINT getMobileLogRecv15()
	{
		 return this.mobileLogRecv15;
	}

	public void setMobileLogRecv15(UINT mobileLogRecv15)
	{
		 this.mobileLogRecv15=mobileLogRecv15;
	}

	@XmlTransient
	public UINT getMobileLogSend15()
	{
		 return this.mobileLogSend15;
	}

	public void setMobileLogSend15(UINT mobileLogSend15)
	{
		 this.mobileLogSend15=mobileLogSend15;
	}

	@XmlTransient
	public UINT getMobileLogRecv16()
	{
		 return this.mobileLogRecv16;
	}

	public void setMobileLogRecv16(UINT mobileLogRecv16)
	{
		 this.mobileLogRecv16=mobileLogRecv16;
	}

	@XmlTransient
	public UINT getMobileLogSend16()
	{
		 return this.mobileLogSend16;
	}

	public void setMobileLogSend16(UINT mobileLogSend16)
	{
		 this.mobileLogSend16=mobileLogSend16;
	}

	@XmlTransient
	public UINT getMobileLogRecv17()
	{
		 return this.mobileLogRecv17;
	}

	public void setMobileLogRecv17(UINT mobileLogRecv17)
	{
		 this.mobileLogRecv17=mobileLogRecv17;
	}

	@XmlTransient
	public UINT getMobileLogSend17()
	{
		 return this.mobileLogSend17;
	}

	public void setMobileLogSend17(UINT mobileLogSend17)
	{
		 this.mobileLogSend17=mobileLogSend17;
	}

	@XmlTransient
	public UINT getMobileLogRecv18()
	{
		 return this.mobileLogRecv18;
	}

	public void setMobileLogRecv18(UINT mobileLogRecv18)
	{
		 this.mobileLogRecv18=mobileLogRecv18;
	}

	@XmlTransient
	public UINT getMobileLogSend18()
	{
		 return this.mobileLogSend18;
	}

	public void setMobileLogSend18(UINT mobileLogSend18)
	{
		 this.mobileLogSend18=mobileLogSend18;
	}

	@XmlTransient
	public UINT getMobileLogRecv19()
	{
		 return this.mobileLogRecv19;
	}

	public void setMobileLogRecv19(UINT mobileLogRecv19)
	{
		 this.mobileLogRecv19=mobileLogRecv19;
	}

	@XmlTransient
	public UINT getMobileLogSend19()
	{
		 return this.mobileLogSend19;
	}

	public void setMobileLogSend19(UINT mobileLogSend19)
	{
		 this.mobileLogSend19=mobileLogSend19;
	}

	@XmlTransient
	public UINT getMobileLogRecv20()
	{
		 return this.mobileLogRecv20;
	}

	public void setMobileLogRecv20(UINT mobileLogRecv20)
	{
		 this.mobileLogRecv20=mobileLogRecv20;
	}

	@XmlTransient
	public UINT getMobileLogSend20()
	{
		 return this.mobileLogSend20;
	}

	public void setMobileLogSend20(UINT mobileLogSend20)
	{
		 this.mobileLogSend20=mobileLogSend20;
	}

	@XmlTransient
	public UINT getMobileLogRecv21()
	{
		 return this.mobileLogRecv21;
	}

	public void setMobileLogRecv21(UINT mobileLogRecv21)
	{
		 this.mobileLogRecv21=mobileLogRecv21;
	}

	@XmlTransient
	public UINT getMobileLogSend21()
	{
		 return this.mobileLogSend21;
	}

	public void setMobileLogSend21(UINT mobileLogSend21)
	{
		 this.mobileLogSend21=mobileLogSend21;
	}

	@XmlTransient
	public UINT getMobileLogRecv22()
	{
		 return this.mobileLogRecv22;
	}

	public void setMobileLogRecv22(UINT mobileLogRecv22)
	{
		 this.mobileLogRecv22=mobileLogRecv22;
	}

	@XmlTransient
	public UINT getMobileLogSend22()
	{
		 return this.mobileLogSend22;
	}

	public void setMobileLogSend22(UINT mobileLogSend22)
	{
		 this.mobileLogSend22=mobileLogSend22;
	}

	@XmlTransient
	public UINT getMobileLogRecv23()
	{
		 return this.mobileLogRecv23;
	}

	public void setMobileLogRecv23(UINT mobileLogRecv23)
	{
		 this.mobileLogRecv23=mobileLogRecv23;
	}

	@XmlTransient
	public UINT getMobileLogSend23()
	{
		 return this.mobileLogSend23;
	}

	public void setMobileLogSend23(UINT mobileLogSend23)
	{
		 this.mobileLogSend23=mobileLogSend23;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("mobileLogRecv00: " + mobileLogRecv00 + "\n");
		sb.append("mobileLogSend00: " + mobileLogSend00 + "\n");
		sb.append("mobileLogRecv01: " + mobileLogRecv01 + "\n");
		sb.append("mobileLogSend01: " + mobileLogSend01 + "\n");
		sb.append("mobileLogRecv02: " + mobileLogRecv02 + "\n");
		sb.append("mobileLogSend02: " + mobileLogSend02 + "\n");
		sb.append("mobileLogRecv03: " + mobileLogRecv03 + "\n");
		sb.append("mobileLogSend03: " + mobileLogSend03 + "\n");
		sb.append("mobileLogRecv04: " + mobileLogRecv04 + "\n");
		sb.append("mobileLogSend04: " + mobileLogSend04 + "\n");
		sb.append("mobileLogRecv05: " + mobileLogRecv05 + "\n");
		sb.append("mobileLogSend05: " + mobileLogSend05 + "\n");
		sb.append("mobileLogRecv06: " + mobileLogRecv06 + "\n");
		sb.append("mobileLogSend06: " + mobileLogSend06 + "\n");
		sb.append("mobileLogRecv07: " + mobileLogRecv07 + "\n");
		sb.append("mobileLogSend07: " + mobileLogSend07 + "\n");
		sb.append("mobileLogRecv08: " + mobileLogRecv08 + "\n");
		sb.append("mobileLogSend08: " + mobileLogSend08 + "\n");
		sb.append("mobileLogRecv09: " + mobileLogRecv09 + "\n");
		sb.append("mobileLogSend09: " + mobileLogSend09 + "\n");
		sb.append("mobileLogRecv10: " + mobileLogRecv10 + "\n");
		sb.append("mobileLogSend10: " + mobileLogSend10 + "\n");
		sb.append("mobileLogRecv11: " + mobileLogRecv11 + "\n");
		sb.append("mobileLogSend11: " + mobileLogSend11 + "\n");
		sb.append("mobileLogRecv12: " + mobileLogRecv12 + "\n");
		sb.append("mobileLogSend12: " + mobileLogSend12 + "\n");
		sb.append("mobileLogRecv13: " + mobileLogRecv13 + "\n");
		sb.append("mobileLogSend13: " + mobileLogSend13 + "\n");
		sb.append("mobileLogRecv14: " + mobileLogRecv14 + "\n");
		sb.append("mobileLogSend14: " + mobileLogSend14 + "\n");
		sb.append("mobileLogRecv15: " + mobileLogRecv15 + "\n");
		sb.append("mobileLogSend15: " + mobileLogSend15 + "\n");
		sb.append("mobileLogRecv16: " + mobileLogRecv16 + "\n");
		sb.append("mobileLogSend16: " + mobileLogSend16 + "\n");
		sb.append("mobileLogRecv17: " + mobileLogRecv17 + "\n");
		sb.append("mobileLogSend17: " + mobileLogSend17 + "\n");
		sb.append("mobileLogRecv18: " + mobileLogRecv18 + "\n");
		sb.append("mobileLogSend18: " + mobileLogSend18 + "\n");
		sb.append("mobileLogRecv19: " + mobileLogRecv19 + "\n");
		sb.append("mobileLogSend19: " + mobileLogSend19 + "\n");
		sb.append("mobileLogRecv20: " + mobileLogRecv20 + "\n");
		sb.append("mobileLogSend20: " + mobileLogSend20 + "\n");
		sb.append("mobileLogRecv21: " + mobileLogRecv21 + "\n");
		sb.append("mobileLogSend21: " + mobileLogSend21 + "\n");
		sb.append("mobileLogRecv22: " + mobileLogRecv22 + "\n");
		sb.append("mobileLogSend22: " + mobileLogSend22 + "\n");
		sb.append("mobileLogRecv23: " + mobileLogRecv23 + "\n");
		sb.append("mobileLogSend23: " + mobileLogSend23 + "\n");


        return sb.toString();
    }
}
