package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * eui64Entry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class eui64Entry extends Entry {

	public UINT eui64High = 
			new UINT();

	public UINT eui64Low = 
			new UINT();

	@XmlTransient
	public UINT getEui64High()
	{
		 return this.eui64High;
	}

	public void setEui64High(UINT eui64High)
	{
		 this.eui64High=eui64High;
	}

	@XmlTransient
	public UINT getEui64Low()
	{
		 return this.eui64Low;
	}

	public void setEui64Low(UINT eui64Low)
	{
		 this.eui64Low=eui64Low;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("eui64High: " + eui64High + "\n");
		sb.append("eui64Low: " + eui64Low + "\n");


        return sb.toString();
    }
}
