package com.aimir.cms.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-01-11T13:33:56.636+09:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://server.ws.cms.aimir.com/", name = "CmsWS")
@XmlSeeAlso({ObjectFactory.class})
public interface CmsWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SearchReq", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.SearchReq")
    @WebMethod
    @ResponseWrapper(localName = "SearchResp", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.SearchResp")
    public SearchResp search(
    		@WebParam(name="AuthCred", targetNamespace = "") 
    		com.aimir.cms.model.AuthCred authCred,
    		@WebParam(name="SearchType", targetNamespace = "") 
    		java.lang.String searchType,
    		@WebParam(name="CMSEnt", targetNamespace = "") 
    		com.aimir.cms.model.CMSEnt cmsEnt)
            throws Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SaveAllReq", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.SaveAllReq")
    @WebMethod
    @ResponseWrapper(localName = "SaveAllResp", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.SaveAllResp")
    public SaveAllResp saveAll(
    		@WebParam(name="AuthCred", targetNamespace = "") 
    		com.aimir.cms.model.AuthCred authCred,
			@WebParam(name="CMSEnt", targetNamespace = "") 
    		com.aimir.cms.model.CMSEnt cmsEnt)
            throws Exception;
    
    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "DataLoadReq", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.DataLoadReq")
    @WebMethod
    @ResponseWrapper(localName = "DataLoadResp", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.DataLoadResp")
    public DataLoadResp dataLoad(
    		@WebParam(name="AuthCred", targetNamespace = "") 
    		com.aimir.cms.model.AuthCred authCred,
			@WebParam(name="CMSEnt", targetNamespace = "") 
    		com.aimir.cms.model.CMSEnt cmsEnt)
            throws Exception;
    
    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "MeterCheckReq", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.MeterCheckReq")
    @WebMethod
    @ResponseWrapper(localName = "MeterCheckResp", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.MeterCheckResp")
    public MeterCheckResp meterCheck(
    		@WebParam(name="AuthCred", targetNamespace = "") 
    		com.aimir.cms.model.AuthCred authCred,
			@WebParam(name="MeterEnt", targetNamespace = "") 
    		com.aimir.cms.model.MeterEnt meterEnt)
            throws Exception;
    
    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "MeterImportReq", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.MeterImportReq")
    @WebMethod
    @ResponseWrapper(localName = "MeterImportResp", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.MeterImportResp")
    public MeterImportResp meterImport(
    		@WebParam(name="AuthCred", targetNamespace = "") 
    		com.aimir.cms.model.AuthCred authCred,
    		@WebParam(name="MeterEnt", targetNamespace = "") 
    		com.aimir.cms.model.MeterEnt meterEnt)
            throws Exception;
    
    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "AddDebtReq", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.AddDebtReq")
    @WebMethod
    @ResponseWrapper(localName = "AddDebtResp", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.AddDebtResp")
    public AddDebtResp addDebt(
    		@WebParam(name="AuthCred", targetNamespace = "") 
    		com.aimir.cms.model.AuthCred authCred,
			@WebParam(name="DebtEnt", targetNamespace = "") 
    		com.aimir.cms.model.DebtEnt debtEnt)
            throws Exception;
    
    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "UpdateDebtReq", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.UpdateDebtReq")
    @WebMethod
    @ResponseWrapper(localName = "UpdateDebtResp", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.UpdateDebtResp")
    public UpdateDebtResp updateDebt(
    		@WebParam(name="AuthCred", targetNamespace = "") 
    		com.aimir.cms.model.AuthCred authCred,
			@WebParam(name="DebtEnt", targetNamespace = "") 
    		com.aimir.cms.model.DebtEnt debtEnt)
            throws Exception;
    
    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetDebtReq", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.GetDebtReq")
    @WebMethod
    @ResponseWrapper(localName = "GetDebtResp", targetNamespace = "http://server.ws.cms.aimir.com/", className = "com.aimir.cms.ws.client.GetDebtResp")
    public GetDebtResp getDebt(
    		@WebParam(name="AuthCred", targetNamespace = "") 
    		com.aimir.cms.model.AuthCred authCred,
			@WebParam(name="DebtEnt", targetNamespace = "") 
    		com.aimir.cms.model.DebtEnt debtEnt)
            throws Exception;
}
