package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * smivarEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class smivarEntry extends Entry {

	public OID smivarOid = 
			new OID();

	public WORD smivarLength = 
			new WORD();

	public OCTET smivarData = 
			new OCTET();

	@XmlTransient
	public OID getSmivarOid()
	{
		 return this.smivarOid;
	}

	public void setSmivarOid(OID smivarOid)
	{
		 this.smivarOid=smivarOid;
	}

	@XmlTransient
	public WORD getSmivarLength()
	{
		 return this.smivarLength;
	}

	public void setSmivarLength(WORD smivarLength)
	{
		 this.smivarLength=smivarLength;
	}

	@XmlTransient
	public OCTET getSmivarData()
	{
		 return this.smivarData;
	}

	public void setSmivarData(OCTET smivarData)
	{
		 this.smivarData=smivarData;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("smivarOid: " + smivarOid + "\n");
		sb.append("smivarLength: " + smivarLength + "\n");
		sb.append("smivarData: " + smivarData + "\n");


        return sb.toString();
    }
}
